import{apartment,numberAt,rows,parse,summary}from'./house.js';
const $=s=>document.querySelector(s),key='etazhi-selection-v1';let selected=[],opened=new Set(),installPrompt;
function status(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error)}
function persist(){try{localStorage.setItem(key,JSON.stringify(selected))}catch{status('Выбор не удалось сохранить на устройстве.',true)}}
function plan(a){let tiles='';for(let p=1;p<=(a.floor===1?13:14);p++){let row,col,span=1;if(p>=4&&p<=11){row=2;col=p-3}else if(p===3){row=3;col=1}else if(p===12){row=3;col=8}else{row=4;col=p===2?1:p===1?2:p===14?7:8;if(a.floor===1&&p===13){col=7;span=2}}let n=numberAt(a.entrance,a.floor,p);tiles+=`<button class="apt ${n===a.n?'chosen':''} ${span===2?'merged':''}" style="grid-row:${row};grid-column:${col}/span ${span}" data-add="${n}" aria-label="Добавить квартиру ${n}${n===a.n?', показана в карточке':''}">${n}${span===2?'<small>3к</small>':''}</button>`}return`<div class="plan-scroll" tabindex="0" aria-label="Схема этажа, прокрутка в стороны"><div class="plan"><div class="orientation" style="grid-row:1">ДЕТСКАЯ ПЛОЩАДКА</div>${tiles}<div class="corridor">Общий коридор</div><div class="exit">Выход ↓</div><div class="orientation" style="grid-row:5">СТОРОНА ПЯТЁРОЧКИ</div></div></div>`}
function stack(n){let a=apartment(n);return(a.stacks.length===2?'<p class="stack-note">На первом этаже квартира занимает позиции 13 и 14. Над ней — две ветви.</p>':'')+`<table><thead><tr><th scope="col">Этаж</th><th scope="col">Квартира</th><th scope="col"><span class="sr-only">Примечание</span></th></tr></thead><tbody>${rows(n).map(r=>`<tr class="${r.nums.includes(n)?'selected':''}"><th scope="row">${String(r.floor).padStart(2,'0')}</th><td>${r.nums.map(v=>`<button data-add="${v}" ${v===n?'aria-current="true"':''}>№${v}</button>`).join('')}</td><td class="row-note">${r.nums.includes(n)?'Выбрана':r.floor===1&&a.pos>=13?'3к · две позиции':''}</td></tr>`).join('')}</tbody></table>`}
function card(n){let a=apartment(n);return`<article class="card" id="apt-${n}" aria-labelledby="title-${n}"><div class="card-top"><div><p class="eyebrow">Квартира</p><h2 id="title-${n}">№ ${n}</h2></div><span class="room-badge">${a.rooms}-комнатная</span></div><div class="facts"><span>Подъезд <strong>${a.entrance}</strong></span><span>Этаж <strong>${a.floor}</strong> из 17</span></div><p class="location">${a.location}</p><div class="plan-heading"><h3>Расположение на этаже</h3><button data-zoom="${n}">Увеличить</button></div>${plan(a)}<p class="map-note">Схема без масштаба · листайте в стороны · нажмите на номер</p><details class="stack" data-stack="${n}" ${opened.has(n)?'open':''}><summary>Квартиры по стояку${a.stacks.length===2?' · 2 ветви':''}</summary><div class="stack-content">${opened.has(n)?stack(n):''}</div></details><div class="card-bottom"><button class="text-button" data-share="${n}">Ссылка на квартиру</button><button class="text-button remove" data-remove="${n}">Убрать из списка</button></div></article>`}
const empty=$('#results').innerHTML;
function render(){let known=new Set(selected);$('#results').querySelectorAll('.card').forEach(el=>{if(!known.has(Number(el.id.slice(4))))el.remove()});if(selected.length){$('#results').querySelector('.empty')?.remove();let added=document.createDocumentFragment();for(let n of selected){if(!document.getElementById(`apt-${n}`)){let t=document.createElement('template');t.innerHTML=card(n);added.append(t.content)}}$('#results').append(added)}else $('#results').innerHTML=empty;$('#count').textContent=selected.length;$('#chips').innerHTML=selected.map(n=>{let a=apartment(n);return`<div class="chip"><a href="#apt-${n}">№ ${n}<small>${a.entrance} подъезд · ${a.floor} этаж</small></a><button data-remove="${n}" aria-label="Убрать квартиру ${n}">×</button></div>`}).join('');for(let id of ['clear','share','copy'])$('#'+id).disabled=!selected.length}
function add(nums){let fresh=nums.filter(n=>!selected.includes(n));selected.push(...fresh);render();persist();status(fresh.length?`Добавлено: ${fresh.length}. Выбрано квартир: ${selected.length}.`:'Эти квартиры уже в списке.');return fresh}
function remove(n){selected=selected.filter(v=>v!==n);opened.delete(n);render();persist();status(`Квартира №${n} убрана. Выбрано: ${selected.length}.`);$('#numbers').focus({preventScroll:true})}
$('#search').addEventListener('submit',e=>{e.preventDefault();try{add(parse($('#numbers').value));$('#numbers').value='';$('#numbers').blur()}catch(err){status(err.message,true)}});
document.addEventListener('click',async e=>{let button=e.target.closest('button');if(!button)return;if(button.dataset.add){let n=Number(button.dataset.add);add([n]);if($('#map-dialog').open)$('#map-dialog').close()}if(button.dataset.remove)remove(Number(button.dataset.remove));if(button.dataset.share)await share([Number(button.dataset.share)]);if(button.dataset.zoom){let a=apartment(Number(button.dataset.zoom));$('#map-title').textContent=`Квартира №${a.n} · ${a.floor} этаж · ${a.entrance} подъезд`;$('#large-map').innerHTML=plan(a);$('#map-dialog').showModal()}if(button.hasAttribute('data-close'))button.closest('dialog').close();if(button.id==='example')add([292])});
document.addEventListener('toggle',e=>{if(!e.target.matches?.('details[data-stack]'))return;let d=e.target,n=Number(d.dataset.stack);if(d.open){opened.add(n);if(!d.querySelector('.stack-content').innerHTML)d.querySelector('.stack-content').innerHTML=stack(n)}else opened.delete(n)},true);
$('#clear').onclick=()=>{selected=[];opened.clear();render();persist();history.replaceState(null,'',location.pathname+location.search);status('Список очищен. Можно начать новый поиск.')};
async function clipboard(text){try{await navigator.clipboard.writeText(text);status('Скопировано. Можно отправить сообщение.')}catch{status('Браузер не разрешил копирование. Используйте адрес страницы для отправки ссылки.',true)}}
async function share(nums){let url=new URL(location.href);url.hash='q='+nums.join(',');try{if(navigator.share){await navigator.share({title:'Этажи · Луговой переулок дом 1',url:url.href})}else await clipboard(url.href)}catch(err){if(err.name!=='AbortError')await clipboard(url.href)}}
$('#share').onclick=()=>share(selected);$('#copy').onclick=()=>clipboard(selected.map(summary).join('\n\n'));
$('#about').onclick=()=>$('#info-dialog').showModal();
fetch('./LICENSE.txt').then(r=>{if(!r.ok)throw Error();return r.text()}).then(t=>$('#license').textContent=t).catch(()=>$('#license').textContent='Не удалось загрузить условия. Повторите открытие приложения при подключении к интернету.');
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null}else $('#install-dialog').showModal()};
function restore(){let q=new URLSearchParams(location.hash.slice(1)).get('q');try{if(q!==null){selected=parse(q)}else{let saved=JSON.parse(localStorage.getItem(key)||'[]');selected=Array.isArray(saved)?[...new Set(saved.filter(n=>Number.isInteger(n)&&n>=1&&n<=711))]:[]}render();if(q!==null){persist();status('Открыта подборка по ссылке.')}}catch{selected=[];render();status('Не удалось прочитать сохранённый выбор или ссылку. Введите номера заново.',true)}}restore();window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#q='))restore()});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('#offline-status').textContent='Приложение подготовлено для работы без интернета на этом устройстве.'}).catch(()=>{$('#offline-status').textContent='Офлайн-доступ пока недоступен. Приложением можно пользоваться с интернетом.'})}
