import{apartment,numberAt,rows,parse}from'./house.js';
const $=s=>document.querySelector(s),key='etazhi-selection-v1';let selected=[],opened=new Set(),installPrompt;
const LANGS=['ru','en','fr','de'];
const lang=()=>LANGS.includes(document.documentElement.lang)?document.documentElement.lang:'ru';
const I={
ru:{apartment:'Квартира',room:n=>`${n}-комнатная`,entrance:'Подъезд',floor:'Этаж',of:'из',playgroundSide:'Со стороны детской площадки',storeSide:'Со стороны Пятёрочки',leftWing:'Левое крыло',rightWing:'Правое крыло',location:'Расположение на этаже',zoom:'Увеличить',playground:'ДЕТСКАЯ ПЛОЩАДКА',corridor:'Общий коридор',exit:'Выход ↓',store:'СТОРОНА ПЯТЁРОЧКИ',mapNote:'Схема без масштаба · листайте в стороны · нажмите на номер',stacks:'Квартиры по стояку',branches:'2 ветви',share:'Ссылка на квартиру',remove:'Убрать из списка',addApt:'Добавить квартиру',shown:', показана в карточке',floorCol:'Этаж',aptCol:'Квартира',noteCol:'Примечание',selectedRow:'Выбрана',threeRooms:'3к · две позиции',stackNote:'На первом этаже квартира занимает позиции 13 и 14. Над ней — две ветви.',chipEntrance:'подъезд',chipFloor:'этаж',removeAria:'Убрать квартиру',saveFail:'Выбор не удалось сохранить на устройстве.',added:(a,b)=>`Добавлено: ${a}. Выбрано квартир: ${b}.`,already:'Эти квартиры уже в списке.',removed:(n,c)=>`Квартира №${n} убрана. Выбрано: ${c}.`,cleared:'Список очищен. Можно начать новый поиск.',copied:'Скопировано. Можно отправить сообщение.',copyFail:'Браузер не разрешил копирование. Используйте адрес страницы для отправки ссылки.',openedLink:'Открыта подборка по ссылке.',restoreFail:'Не удалось прочитать сохранённый выбор или ссылку. Введите номера заново.',mapTitle:(n,f,e)=>`Квартира №${n} · ${f} этаж · ${e} подъезд`,shareTitle:'Этажи · Луговой переулок дом 1',address:'Луговой переулок дом 1',summaryFloor:'этаж',parseEmpty:'Введите номер квартиры.',parseExample:'Пример ввода: 13, 292, 475–480.',parseRange:'Квартиры — от 1 до 711. Диапазон укажите по возрастанию.',parseOne:'Введите хотя бы один номер.'},
en:{apartment:'Apartment',room:n=>`${n}-room`,entrance:'Entrance',floor:'Floor',of:'of',playgroundSide:'On the playground side',storeSide:'On the Pyaterochka side',leftWing:'Left wing',rightWing:'Right wing',location:'Location on the floor',zoom:'Zoom in',playground:'PLAYGROUND',corridor:'Common corridor',exit:'Exit ↓',store:'PYATEROCHKA SIDE',mapNote:'Diagram not to scale · scroll sideways · tap a number',stacks:'Apartments in this vertical stack',branches:'2 branches',share:'Apartment link',remove:'Remove from list',addApt:'Add apartment',shown:', shown in this card',floorCol:'Floor',aptCol:'Apartment',noteCol:'Note',selectedRow:'Selected',threeRooms:'3-room · two positions',stackNote:'On the first floor this apartment occupies positions 13 and 14. Above it there are two branches.',chipEntrance:'entrance',chipFloor:'floor',removeAria:'Remove apartment',saveFail:'Could not save the selection on this device.',added:(a,b)=>`Added: ${a}. Apartments selected: ${b}.`,already:'These apartments are already in the list.',removed:(n,c)=>`Apartment №${n} removed. Selected: ${c}.`,cleared:'List cleared. You can start a new search.',copied:'Copied. You can send it now.',copyFail:'The browser did not allow copying. Use the page address to share the link.',openedLink:'Selection opened from a link.',restoreFail:'Could not read the saved selection or link. Enter the apartment numbers again.',mapTitle:(n,f,e)=>`Apartment №${n} · floor ${f} · entrance ${e}`,shareTitle:'Floors · Lugovoy Lane 1',address:'Lugovoy Lane 1',summaryFloor:'floor',parseEmpty:'Enter an apartment number.',parseExample:'Example: 13, 292, 475–480.',parseRange:'Apartment numbers are from 1 to 711. Enter ranges in ascending order.',parseOne:'Enter at least one number.'},
fr:{apartment:'Appartement',room:n=>`${n} pièce${n>1?'s':''}`,entrance:'Entrée',floor:'Étage',of:'sur',playgroundSide:'Côté aire de jeux',storeSide:'Côté Pyaterochka',leftWing:'Aile gauche',rightWing:'Aile droite',location:'Emplacement à l’étage',zoom:'Agrandir',playground:'AIRE DE JEUX',corridor:'Couloir commun',exit:'Sortie ↓',store:'CÔTÉ PYATEROCHKA',mapNote:'Schéma non à l’échelle · faites défiler horizontalement · appuyez sur un numéro',stacks:'Appartements dans la colonne',branches:'2 branches',share:'Lien vers l’appartement',remove:'Retirer de la liste',addApt:'Ajouter l’appartement',shown:', affiché dans cette fiche',floorCol:'Étage',aptCol:'Appartement',noteCol:'Remarque',selectedRow:'Sélectionné',threeRooms:'3 pièces · deux positions',stackNote:'Au premier étage, cet appartement occupe les positions 13 et 14. Au-dessus, il y a deux branches.',chipEntrance:'entrée',chipFloor:'étage',removeAria:'Retirer l’appartement',saveFail:'Impossible d’enregistrer la sélection sur cet appareil.',added:(a,b)=>`Ajouté : ${a}. Appartements sélectionnés : ${b}.`,already:'Ces appartements sont déjà dans la liste.',removed:(n,c)=>`Appartement №${n} retiré. Sélectionnés : ${c}.`,cleared:'Liste effacée. Vous pouvez lancer une nouvelle recherche.',copied:'Copié. Vous pouvez maintenant l’envoyer.',copyFail:'Le navigateur n’autorise pas la copie. Utilisez l’adresse de la page pour partager le lien.',openedLink:'Sélection ouverte depuis un lien.',restoreFail:'Impossible de lire la sélection enregistrée ou le lien. Saisissez de nouveau les numéros.',mapTitle:(n,f,e)=>`Appartement №${n} · étage ${f} · entrée ${e}`,shareTitle:'Étages · 1, ruelle Lugovoy',address:'1, ruelle Lugovoy',summaryFloor:'étage',parseEmpty:'Saisissez un numéro d’appartement.',parseExample:'Exemple : 13, 292, 475–480.',parseRange:'Les appartements vont de 1 à 711. Saisissez les plages dans l’ordre croissant.',parseOne:'Saisissez au moins un numéro.'},
de:{apartment:'Wohnung',room:n=>`${n}-Zimmer`,entrance:'Eingang',floor:'Etage',of:'von',playgroundSide:'Zur Spielplatzseite',storeSide:'Zur Pyaterochka-Seite',leftWing:'Linker Flügel',rightWing:'Rechter Flügel',location:'Lage auf der Etage',zoom:'Vergrößern',playground:'SPIELPLATZ',corridor:'Gemeinsamer Flur',exit:'Ausgang ↓',store:'SEITE ZUR PYATEROCHKA',mapNote:'Schema nicht maßstabsgetreu · seitlich scrollen · Nummer antippen',stacks:'Wohnungen im Strang',branches:'2 Zweige',share:'Link zur Wohnung',remove:'Aus Liste entfernen',addApt:'Wohnung hinzufügen',shown:', in dieser Karte angezeigt',floorCol:'Etage',aptCol:'Wohnung',noteCol:'Hinweis',selectedRow:'Ausgewählt',threeRooms:'3-Zimmer · zwei Positionen',stackNote:'Im ersten Stock belegt diese Wohnung die Positionen 13 und 14. Darüber gibt es zwei Zweige.',chipEntrance:'Eingang',chipFloor:'Etage',removeAria:'Wohnung entfernen',saveFail:'Die Auswahl konnte auf diesem Gerät nicht gespeichert werden.',added:(a,b)=>`Hinzugefügt: ${a}. Wohnungen ausgewählt: ${b}.`,already:'Diese Wohnungen sind bereits in der Liste.',removed:(n,c)=>`Wohnung №${n} entfernt. Ausgewählt: ${c}.`,cleared:'Liste geleert. Sie können eine neue Suche starten.',copied:'Kopiert. Sie können die Daten jetzt senden.',copyFail:'Der Browser hat das Kopieren nicht erlaubt. Verwenden Sie die Seitenadresse, um den Link zu teilen.',openedLink:'Auswahl über einen Link geöffnet.',restoreFail:'Gespeicherte Auswahl oder Link konnten nicht gelesen werden. Geben Sie die Nummern erneut ein.',mapTitle:(n,f,e)=>`Wohnung №${n} · Etage ${f} · Eingang ${e}`,shareTitle:'Etagen · Lugovoy-Gasse 1',address:'Lugovoy-Gasse 1',summaryFloor:'Etage',parseEmpty:'Wohnungsnummer eingeben.',parseExample:'Beispiel: 13, 292, 475–480.',parseRange:'Wohnungsnummern reichen von 1 bis 711. Bereiche aufsteigend eingeben.',parseOne:'Mindestens eine Nummer eingeben.'}
};
const t=()=>I[lang()];
function status(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error)}
function persist(){try{localStorage.setItem(key,JSON.stringify(selected))}catch{status(t().saveFail,true)}}
function loc(a){const x=t();return a.location==='Со стороны Пятёрочки'?x.storeSide:a.location==='Левое крыло'?x.leftWing:a.location==='Правое крыло'?x.rightWing:x.playgroundSide}
function plan(a){const x=t();let tiles='';for(let p=1;p<=(a.floor===1?13:14);p++){let row,col,span=1;if(p>=4&&p<=11){row=2;col=p-3}else if(p===3){row=3;col=1}else if(p===12){row=3;col=8}else{row=4;col=p===2?1:p===1?2:p===14?7:8;if(a.floor===1&&p===13){col=7;span=2}}let n=numberAt(a.entrance,a.floor,p);tiles+=`<button class="apt ${n===a.n?'chosen':''} ${span===2?'merged':''}" style="grid-row:${row};grid-column:${col}/span ${span}" data-add="${n}" aria-label="${x.addApt} ${n}${n===a.n?x.shown:''}">${n}${span===2?'<small>3к</small>':''}</button>`}return`<div class="plan-scroll" tabindex="0" aria-label="${x.location}"><div class="plan"><div class="orientation" style="grid-row:1">${x.playground}</div>${tiles}<div class="corridor">${x.corridor}</div><div class="exit">${x.exit}</div><div class="orientation" style="grid-row:5">${x.store}</div></div></div>`}
function stack(n){const x=t();let a=apartment(n);return(a.stacks.length===2?`<p class="stack-note">${x.stackNote}</p>`:'')+`<table><thead><tr><th scope="col">${x.floorCol}</th><th scope="col">${x.aptCol}</th><th scope="col"><span class="sr-only">${x.noteCol}</span></th></tr></thead><tbody>${rows(n).map(r=>`<tr class="${r.nums.includes(n)?'selected':''}"><th scope="row">${String(r.floor).padStart(2,'0')}</th><td>${r.nums.map(v=>`<button data-add="${v}" ${v===n?'aria-current="true"':''}>№${v}</button>`).join('')}</td><td class="row-note">${r.nums.includes(n)?x.selectedRow:r.floor===1&&a.pos>=13?x.threeRooms:''}</td></tr>`).join('')}</tbody></table>`}
function card(n){const x=t();let a=apartment(n);return`<article class="card" id="apt-${n}" aria-labelledby="title-${n}"><div class="card-top"><div><p class="eyebrow">${x.apartment}</p><h2 id="title-${n}">№ ${n}</h2></div><span class="room-badge">${x.room(a.rooms)}</span></div><div class="facts"><span>${x.entrance} <strong>${a.entrance}</strong></span><span>${x.floor} <strong>${a.floor}</strong> ${x.of} 17</span></div><p class="location">${loc(a)}</p><div class="plan-heading"><h3>${x.location}</h3><button data-zoom="${n}">${x.zoom}</button></div>${plan(a)}<p class="map-note">${x.mapNote}</p><details class="stack" data-stack="${n}" ${opened.has(n)?'open':''}><summary>${x.stacks}${a.stacks.length===2?` · ${x.branches}`:''}</summary><div class="stack-content">${opened.has(n)?stack(n):''}</div></details><div class="card-bottom"><button class="text-button" data-share="${n}">${x.share}</button><button class="text-button remove" data-remove="${n}">${x.remove}</button></div></article>`}
const empty=$('#results').innerHTML;
function render(){let known=new Set(selected);$('#results').querySelectorAll('.card').forEach(el=>{if(!known.has(Number(el.id.slice(4))))el.remove()});if(selected.length){$('#results').querySelector('.empty')?.remove();let added=document.createDocumentFragment();for(let n of selected){let existing=document.getElementById(`apt-${n}`);if(existing)existing.remove();let tpl=document.createElement('template');tpl.innerHTML=card(n);added.append(tpl.content)}$('#results').append(added)}else $('#results').innerHTML=empty;$('#count').textContent=selected.length;const x=t();$('#chips').innerHTML=selected.map(n=>{let a=apartment(n);return`<div class="chip"><a href="#apt-${n}">№ ${n}<small>${a.entrance} ${x.chipEntrance} · ${a.floor} ${x.chipFloor}</small></a><button data-remove="${n}" aria-label="${x.removeAria} ${n}">×</button></div>`}).join('');for(let id of ['clear','share','copy'])$('#'+id).disabled=!selected.length}
function localParseError(msg){const x=t();if(lang()==='ru')return msg;if(msg.includes('Введите номер квартиры'))return x.parseEmpty;if(msg.includes('Пример ввода'))return x.parseExample;if(msg.includes('Диапазон')||msg.includes('от 1 до 711'))return x.parseRange;if(msg.includes('хотя бы один'))return x.parseOne;return msg}
function add(nums){let fresh=nums.filter(n=>!selected.includes(n));selected.push(...fresh);render();persist();const x=t();status(fresh.length?x.added(fresh.length,selected.length):x.already);return fresh}
function remove(n){selected=selected.filter(v=>v!==n);opened.delete(n);render();persist();status(t().removed(n,selected.length));$('#numbers').focus({preventScroll:true})}
$('#search').addEventListener('submit',e=>{e.preventDefault();try{add(parse($('#numbers').value));$('#numbers').value='';$('#numbers').blur()}catch(err){status(localParseError(err.message),true)}});
document.addEventListener('click',async e=>{let button=e.target.closest('button');if(!button)return;if(button.dataset.add){let n=Number(button.dataset.add);add([n]);if($('#map-dialog').open)$('#map-dialog').close()}if(button.dataset.remove)remove(Number(button.dataset.remove));if(button.dataset.share)await share([Number(button.dataset.share)]);if(button.dataset.zoom){let a=apartment(Number(button.dataset.zoom));$('#map-title').textContent=t().mapTitle(a.n,a.floor,a.entrance);$('#large-map').innerHTML=plan(a);$('#map-dialog').showModal()}if(button.hasAttribute('data-close'))button.closest('dialog').close();if(button.id==='example')add([292])});
document.addEventListener('toggle',e=>{if(!e.target.matches?.('details[data-stack]'))return;let d=e.target,n=Number(d.dataset.stack);if(d.open){opened.add(n);if(!d.querySelector('.stack-content').innerHTML)d.querySelector('.stack-content').innerHTML=stack(n)}else opened.delete(n)},true);
$('#clear').onclick=()=>{selected=[];opened.clear();render();persist();history.replaceState(null,'',location.pathname+location.search);status(t().cleared)};
async function clipboard(text){try{await navigator.clipboard.writeText(text);status(t().copied)}catch{status(t().copyFail,true)}}
function localizedSummary(n){const x=t(),a=apartment(n);return`${x.apartment} №${n} · ${x.room(a.rooms)}\n${x.address}\n${x.entrance} ${a.entrance} · ${x.floor.toLowerCase()} ${a.floor}\n${loc(a)}\n`+rows(n).map(r=>`${r.floor} ${x.summaryFloor}: ${r.nums.join(', ')}`).join('\n')}
async function share(nums){let url=new URL(location.href);url.hash='q='+nums.join(',');try{if(navigator.share){await navigator.share({title:t().shareTitle,url:url.href})}else await clipboard(url.href)}catch(err){if(err.name!=='AbortError')await clipboard(url.href)}}
$('#share').onclick=()=>share(selected);$('#copy').onclick=()=>clipboard(selected.map(localizedSummary).join('\n\n'));
$('#about').onclick=()=>$('#info-dialog').showModal();
fetch('./LICENSE.txt').then(r=>{if(!r.ok)throw Error();return r.text()}).then(txt=>{$('#license').textContent=txt;queueMicrotask(()=>window.applyFullI18n?.())}).catch(()=>{$('#license').textContent='Не удалось загрузить условия. Повторите открытие приложения при подключении к интернету.';queueMicrotask(()=>window.applyFullI18n?.())});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null}else $('#install-dialog').showModal()};
function restore(){let q=new URLSearchParams(location.hash.slice(1)).get('q');try{if(q!==null){selected=parse(q)}else{let saved=JSON.parse(localStorage.getItem(key)||'[]');selected=Array.isArray(saved)?[...new Set(saved.filter(n=>Number.isInteger(n)&&n>=1&&n<=711))]:[]}render();if(q!==null){persist();status(t().openedLink)}}catch{selected=[];render();status(t().restoreFail,true)}}restore();window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#q='))restore()});
new MutationObserver(()=>{render();const open=$('#map-dialog');if(open?.open){const n=Number(open.querySelector('[data-add].chosen')?.dataset.add);if(n){const a=apartment(n);$('#map-title').textContent=t().mapTitle(a.n,a.floor,a.entrance);$('#large-map').innerHTML=plan(a)}}}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('#offline-status').textContent='Приложение подготовлено для работы без интернета на этом устройстве.'}).catch(()=>{$('#offline-status').textContent='Офлайн-доступ пока недоступен. Приложением можно пользоваться с интернетом.'})}
