(()=>{
  const T={
    ru:{title:'Bubble Shooter',back:'← К списку игр',newGame:'Новая игра',score:'Очки',level:'Уровень',best:'Рекорд',hint:'Ведите пальцем по полю, чтобы прицелиться, и отпустите для выстрела. Группы из 3+ одинаковых шариков лопаются.',win:'Уровень пройден!',lose:'Шарики опустились слишком низко',next:'Следующий уровень',again:'Начать заново',play:'Играть',card:'Лопайте группы одинаковых шариков.',tip:'Прицеливайтесь пальцем · отпустите для выстрела'},
    en:{title:'Bubble Shooter',back:'← Back to games',newGame:'New game',score:'Score',level:'Level',best:'Best',hint:'Drag your finger to aim and release to shoot. Groups of 3 or more matching bubbles pop.',win:'Level complete!',lose:'The bubbles reached the bottom',next:'Next level',again:'Start again',play:'Play',card:'Pop groups of matching bubbles.',tip:'Aim with your finger · release to shoot'},
    fr:{title:'Bubble Shooter',back:'← Retour aux jeux',newGame:'Nouvelle partie',score:'Score',level:'Niveau',best:'Record',hint:'Glissez le doigt pour viser puis relâchez pour tirer. Les groupes de 3 bulles identiques ou plus éclatent.',win:'Niveau terminé !',lose:'Les bulles sont descendues trop bas',next:'Niveau suivant',again:'Recommencer',play:'Jouer',card:'Faites éclater les groupes de bulles identiques.',tip:'Visez avec le doigt · relâchez pour tirer'},
    de:{title:'Bubble Shooter',back:'← Zurück zu den Spielen',newGame:'Neues Spiel',score:'Punkte',level:'Stufe',best:'Rekord',hint:'Mit dem Finger zielen und zum Schießen loslassen. Gruppen aus 3 oder mehr gleichen Kugeln platzen.',win:'Stufe geschafft!',lose:'Die Kugeln sind zu weit nach unten gekommen',next:'Nächste Stufe',again:'Neu starten',play:'Spielen',card:'Gruppen gleicher Kugeln platzen lassen.',tip:'Mit dem Finger zielen · zum Schießen loslassen'}
  };
  const L=()=>T[document.documentElement.lang]?document.documentElement.lang:'ru';
  const COLS=9,ROWS=13,PALETTE=['#ef5350','#42a5f5','#66bb6a','#ffca28','#ab47bc','#ff8a65'];
  let view,canvas,ctx,grid=[],score=0,level=1,best=Number(localStorage.getItem('lugovoy-bubble-best')||0),current=0,next=1,aimX=230,aimY=200,shot=null,raf=0,running=false,locked=false;

  function colorsForLevel(){return Math.min(6,3+Math.floor((level-1)/2));}
  function rowsForLevel(){return Math.min(8,4+Math.floor((level-1)/2));}
  function cellPos(r,c){const radius=22,dx=47,dy=40.5,offset=(r%2)*23.5;return {x:24+offset+c*dx,y:25+r*dy,radius};}
  function valid(r,c){return r>=0&&r<ROWS&&c>=0&&c<COLS&&!(r%2&&c===COLS-1);}
  function neighbors(r,c){const even=[[-1,-1],[-1,0],[0,-1],[0,1],[1,-1],[1,0]],odd=[[-1,0],[-1,1],[0,-1],[0,1],[1,0],[1,1]];return (r%2?odd:even).map(([dr,dc])=>[r+dr,c+dc]).filter(([rr,cc])=>valid(rr,cc));}
  function randColor(){return Math.floor(Math.random()*colorsForLevel());}
  function setupLevel(resetScore=false){cancelAnimationFrame(raf);running=false;locked=false;shot=null;if(resetScore)score=0;grid=Array.from({length:ROWS},()=>Array(COLS).fill(null));const rows=rowsForLevel();for(let r=0;r<rows;r++)for(let c=0;c<COLS;c++)if(valid(r,c))grid[r][c]=randColor();current=randColor();next=randColor();aimX=230;aimY=170;hideOverlay();draw();stats();}
  function ensureCard(){const g=document.querySelector('.games-grid');if(!g)return;let card=g.querySelector('[data-game="bubble-shooter"]');if(!card){card=document.createElement('button');card.type='button';card.className='game-card game-ready';card.dataset.game='bubble-shooter';card.innerHTML='<span class="game-icon" aria-hidden="true">🫧</span><span><strong></strong><small></small><span class="game-soon"></span></span>';g.appendChild(card);}const t=T[L()];card.querySelector('strong').textContent=t.title;card.querySelector('small').textContent=t.card;card.querySelector('.game-soon').textContent=t.play;}
  function build(){const main=document.getElementById('top');if(!main)return;view=document.createElement('section');view.className='bubble-view';view.hidden=true;view.innerHTML=`<button type="button" class="bubble-back"></button><div class="bubble-head"><div><h2>🫧 Bubble Shooter</h2><p class="bubble-help"></p></div><button type="button" class="bubble-new"></button></div><div class="bubble-stats"><div><span class="bubble-score-label"></span><strong data-bubble-score>0</strong></div><div><span class="bubble-level-label"></span><strong data-bubble-level>1</strong></div><div><span class="bubble-best-label"></span><strong data-bubble-best>0</strong></div></div><div class="bubble-stage"><canvas width="460" height="620"></canvas><div class="bubble-overlay" hidden><strong></strong><button type="button"></button></div></div><p class="bubble-tip"></p>`;main.appendChild(view);canvas=view.querySelector('canvas');ctx=canvas.getContext('2d');view.querySelector('.bubble-back').addEventListener('click',showGames);view.querySelector('.bubble-new').addEventListener('click',()=>{level=1;setupLevel(true)});view.querySelector('.bubble-overlay button').addEventListener('click',()=>{if(view.querySelector('.bubble-overlay').dataset.type==='win'){level++;setupLevel(false)}else{level=1;setupLevel(true)}});const stage=view.querySelector('.bubble-stage');const point=e=>{const b=canvas.getBoundingClientRect(),sx=canvas.width/b.width,sy=canvas.height/b.height;return {x:(e.clientX-b.left)*sx,y:(e.clientY-b.top)*sy};};stage.addEventListener('pointerdown',e=>{if(locked)return;stage.setPointerCapture?.(e.pointerId);const p=point(e);aimX=p.x;aimY=p.y;draw();});stage.addEventListener('pointermove',e=>{if(locked||!(e.buttons&1))return;const p=point(e);aimX=p.x;aimY=p.y;draw();});stage.addEventListener('pointerup',e=>{if(locked)return;const p=point(e);aimX=p.x;aimY=p.y;fire();});document.addEventListener('click',e=>{const c=e.target.closest('[data-game="bubble-shooter"]');if(c){e.preventDefault();e.stopPropagation();showGame();}},true);apply();setupLevel(true);ensureCard();const g=document.querySelector('.games-grid');if(g)new MutationObserver(()=>ensureCard()).observe(g,{childList:true});new MutationObserver(()=>requestAnimationFrame(()=>{apply();ensureCard()})).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});}
  function hideOthers(){['.new-home-nav','.games-view','.game2048-view','.snake-view','.tictactoe-view','.memory-view','.minesweeper-view','.checkers-view','.new-ui-search-view'].forEach(s=>document.querySelector(s)?.setAttribute('hidden',''));}
  function showGame(){hideOthers();view.hidden=false;view.scrollIntoView({behavior:'smooth',block:'start'});draw();}
  function showGames(){cancelAnimationFrame(raf);running=false;view.hidden=true;const g=document.querySelector('.games-view');if(g){g.hidden=false;ensureCard();g.scrollIntoView({behavior:'smooth',block:'start'});}}
  function fire(){if(locked||shot)return;const sx=230,sy=575,dx=aimX-sx,dy=Math.min(-20,aimY-sy),len=Math.hypot(dx,dy)||1;shot={x:sx,y:sy,vx:dx/len*520,vy:dy/len*520,color:current};current=next;next=randColor();locked=true;running=true;let last=performance.now();const loop=now=>{if(!running)return;const dt=Math.min(.025,(now-last)/1000);last=now;stepShot(dt);draw();if(running)raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);}
  function stepShot(dt){shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;const rad=22;if(shot.x<rad){shot.x=rad;shot.vx=Math.abs(shot.vx)}if(shot.x>460-rad){shot.x=460-rad;shot.vx=-Math.abs(shot.vx)}let hit=shot.y<=rad;let near=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(grid[r][c]!==null){const p=cellPos(r,c),d=Math.hypot(shot.x-p.x,shot.y-p.y);if(d<44){hit=true;near.push([r,c,d])}}if(hit)attach(near);}
  function attach(near){running=false;cancelAnimationFrame(raf);let candidates=[];if(near.length){near.sort((a,b)=>a[2]-b[2]);for(const [r,c] of near.slice(0,4))for(const [rr,cc] of neighbors(r,c))if(grid[rr][cc]===null){const p=cellPos(rr,cc);candidates.push([rr,cc,Math.hypot(shot.x-p.x,shot.y-p.y)])}}else{for(let c=0;c<COLS;c++)if(valid(0,c)&&grid[0][c]===null){const p=cellPos(0,c);candidates.push([0,c,Math.abs(shot.x-p.x)])}}if(!candidates.length){for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(valid(r,c)&&grid[r][c]===null){const p=cellPos(r,c);candidates.push([r,c,Math.hypot(shot.x-p.x,shot.y-p.y)])}}candidates.sort((a,b)=>a[2]-b[2]);const place=candidates[0];if(!place){lose();return;}const [r,c]=place;grid[r][c]=shot.color;shot=null;resolve(r,c);locked=false;draw();}
  function floodSame(sr,sc){const color=grid[sr][sc],seen=new Set([`${sr},${sc}`]),q=[[sr,sc]],out=[];while(q.length){const [r,c]=q.shift();out.push([r,c]);for(const [rr,cc] of neighbors(r,c)){const k=`${rr},${cc}`;if(!seen.has(k)&&grid[rr][cc]===color){seen.add(k);q.push([rr,cc])}}}return out;}
  function resolve(r,c){const group=floodSame(r,c);if(group.length>=3){group.forEach(([rr,cc])=>grid[rr][cc]=null);score+=group.length*10;dropFloating();}if(score>best){best=score;localStorage.setItem('lugovoy-bubble-best',String(best))}stats();if(isClear())win();else if(reachedBottom())lose();}
  function dropFloating(){const connected=new Set(),q=[];for(let c=0;c<COLS;c++)if(valid(0,c)&&grid[0][c]!==null){connected.add(`0,${c}`);q.push([0,c])}while(q.length){const [r,c]=q.shift();for(const [rr,cc] of neighbors(r,c)){const k=`${rr},${cc}`;if(grid[rr][cc]!==null&&!connected.has(k)){connected.add(k);q.push([rr,cc])}}}let dropped=0;for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(grid[r][c]!==null&&!connected.has(`${r},${c}`)){grid[r][c]=null;dropped++}score+=dropped*15;}
  function isClear(){return grid.every(row=>row.every(v=>v===null));}
  function reachedBottom(){for(let r=ROWS-2;r<ROWS;r++)for(let c=0;c<COLS;c++)if(valid(r,c)&&grid[r][c]!==null)return true;return false;}
  function win(){locked=true;showOverlay('win');}
  function lose(){running=false;locked=true;shot=null;showOverlay('lose');}
  function showOverlay(type){const o=view.querySelector('.bubble-overlay'),t=T[L()];o.hidden=false;o.dataset.type=type;o.querySelector('strong').textContent=type==='win'?t.win:t.lose;o.querySelector('button').textContent=type==='win'?t.next:t.again;}
  function hideOverlay(){if(view)view.querySelector('.bubble-overlay').hidden=true;}
  function stats(){if(!view)return;view.querySelector('[data-bubble-score]').textContent=score;view.querySelector('[data-bubble-level]').textContent=level;view.querySelector('[data-bubble-best]').textContent=best;}
  function bubble(x,y,color,r=22){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=PALETTE[color];ctx.fill();ctx.beginPath();ctx.arc(x-r*.32,y-r*.35,r*.25,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.48)';ctx.fill();ctx.strokeStyle='rgba(0,0,0,.12)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();}
  function draw(){if(!ctx)return;ctx.clearRect(0,0,460,620);const grad=ctx.createLinearGradient(0,0,0,620);grad.addColorStop(0,'#eef9ff');grad.addColorStop(1,'#f7fbf8');ctx.fillStyle=grad;ctx.fillRect(0,0,460,620);ctx.strokeStyle='rgba(18,110,101,.12)';ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(0,520);ctx.lineTo(460,520);ctx.stroke();ctx.setLineDash([]);for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(valid(r,c)&&grid[r][c]!==null){const p=cellPos(r,c);bubble(p.x,p.y,grid[r][c])}const sx=230,sy=575;if(!shot){let dx=aimX-sx,dy=Math.min(-20,aimY-sy),len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;ctx.strokeStyle='rgba(23,49,63,.35)';ctx.lineWidth=3;ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+dx*160,sy+dy*160);ctx.stroke();ctx.setLineDash([]);bubble(sx,sy,current,23);bubble(410,580,next,14);ctx.fillStyle='#67808c';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText('NEXT',410,607)}else bubble(shot.x,shot.y,shot.color,22);}
  function apply(){if(!view)return;const t=T[L()];view.querySelector('.bubble-head h2').textContent=`🫧 ${t.title}`;view.querySelector('.bubble-back').textContent=t.back;view.querySelector('.bubble-new').textContent=t.newGame;view.querySelector('.bubble-help').textContent=t.hint;view.querySelector('.bubble-score-label').textContent=t.score;view.querySelector('.bubble-level-label').textContent=t.level;view.querySelector('.bubble-best-label').textContent=t.best;view.querySelector('.bubble-tip').textContent=t.tip;const o=view.querySelector('.bubble-overlay');if(!o.hidden)showOverlay(o.dataset.type||'lose');ensureCard();stats();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(build,0));else setTimeout(build,0);
})();