(()=>{
  const T={
    ru:{close:'Закрыть',phoneQ:'Что сделать с номером?',emailQ:'Что сделать с почтой?',addressQ:'Что сделать с адресом?',copyPhone:'📋 Копировать номер',call:'📞 Позвонить',copyEmail:'📋 Копировать почту',write:'✉️ Написать письмо',copyAddress:'📋 Копировать адрес',map:'🗺️ Открыть в Яндекс Картах',callShort:'Позвонить',addressActions:'Действия с адресом:'},
    en:{close:'Close',phoneQ:'What would you like to do with this number?',emailQ:'What would you like to do with this email?',addressQ:'What would you like to do with this address?',copyPhone:'📋 Copy number',call:'📞 Call',copyEmail:'📋 Copy email',write:'✉️ Write email',copyAddress:'📋 Copy address',map:'🗺️ Open in Yandex Maps',callShort:'Call',addressActions:'Address actions:'},
    fr:{close:'Fermer',phoneQ:'Que faire avec ce numéro ?',emailQ:'Que faire avec cette adresse e-mail ?',addressQ:'Que faire avec cette adresse ?',copyPhone:'📋 Copier le numéro',call:'📞 Appeler',copyEmail:'📋 Copier l’e-mail',write:'✉️ Écrire un e-mail',copyAddress:'📋 Copier l’adresse',map:'🗺️ Ouvrir dans Yandex Maps',callShort:'Appeler',addressActions:'Actions avec l’adresse :'},
    de:{close:'Schließen',phoneQ:'Was möchten Sie mit dieser Nummer tun?',emailQ:'Was möchten Sie mit dieser E-Mail tun?',addressQ:'Was möchten Sie mit dieser Adresse tun?',copyPhone:'📋 Nummer kopieren',call:'📞 Anrufen',copyEmail:'📋 E-Mail kopieren',write:'✉️ E-Mail schreiben',copyAddress:'📋 Adresse kopieren',map:'🗺️ In Yandex Maps öffnen',callShort:'Anrufen',addressActions:'Aktionen für Adresse:'}
  };
  const lang=()=>T[document.documentElement.lang]?document.documentElement.lang:'ru',t=()=>T[lang()];
  const style=document.createElement('style');style.textContent=`.contact-actionable{cursor:pointer;border-radius:8px;transition:background-color .12s ease,color .12s ease}.contact-actionable:hover{background:#e6f1ee;color:var(--green)}.contact-actionable:active{background:#dff1e8}#contact-action-dialog{max-width:420px;width:calc(100% - 32px);padding:20px}#contact-action-dialog .contact-action-title{font-size:1.05rem;font-weight:800;margin:0 44px 8px 0;overflow-wrap:anywhere}#contact-action-dialog .contact-action-subtitle{color:var(--muted);font-size:.9rem;margin:0 0 16px;overflow-wrap:anywhere}#contact-action-dialog .contact-action-buttons{display:grid;gap:10px}#contact-action-dialog .contact-action-buttons button{width:100%;text-align:left;min-height:52px}#contact-action-dialog .contact-action-buttons .primary-action{background:var(--green);border-color:var(--green);color:#fff}#contact-action-dialog .contact-action-close{position:absolute;right:16px;top:16px;min-width:44px}@media(max-width:760px){.passport-phone,.management-phone{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:7px!important;white-space:nowrap!important;padding:12px 10px!important}.passport-phone{font-size:clamp(.78rem,3.35vw,.94rem)!important}.management-phone{font-size:clamp(.88rem,3.8vw,1rem)!important}.passport-phone::after,.management-phone::after{display:block!important;content:attr(data-call-label)!important;font-size:.68rem!important;font-weight:700!important;color:var(--muted)!important;white-space:nowrap!important}}`;
  document.head.appendChild(style);
  const dialog=document.createElement('dialog');dialog.id='contact-action-dialog';dialog.innerHTML='<button type="button" class="contact-action-close">✕</button><div class="contact-action-title"></div><div class="contact-action-subtitle"></div><div class="contact-action-buttons"></div>';document.body.appendChild(dialog);
  const title=dialog.querySelector('.contact-action-title'),subtitle=dialog.querySelector('.contact-action-subtitle'),buttons=dialog.querySelector('.contact-action-buttons'),close=dialog.querySelector('.contact-action-close');close.addEventListener('click',()=>dialog.close());
  async function writeClipboard(text){try{await navigator.clipboard.writeText(text);return true}catch{try{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();return true}catch{return false}}}
  async function copy(text){await writeClipboard(text);dialog.close()}
  function openMenu(kind,value,label,href){const x=t();title.textContent=label;subtitle.textContent=kind==='phone'?x.phoneQ:kind==='email'?x.emailQ:x.addressQ;buttons.innerHTML='';const add=(text,primary,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;if(primary)b.className='primary-action';b.addEventListener('click',fn);buttons.appendChild(b)};if(kind==='phone'){add(x.copyPhone,false,()=>copy(label));add(x.call,true,()=>{dialog.close();location.href=href})}else if(kind==='email'){add(x.copyEmail,false,()=>copy(value));add(x.write,true,()=>{dialog.close();location.href=href})}else{add(x.copyAddress,false,()=>copy(value));add(x.map,true,()=>{dialog.close();window.open('https://yandex.ru/maps/?text='+encodeURIComponent(value),'_blank','noopener')})}close.setAttribute('aria-label',x.close);dialog.showModal()}
  function mark(root=document){const x=t();root.querySelectorAll?.('a[href^="tel:"]').forEach(el=>el.dataset.callLabel=x.callShort);root.querySelectorAll?.('.management-address,.passport-card p').forEach(el=>{const strong=el.querySelector('strong');if(!strong)return;const txt=strong.textContent.trim().toLowerCase();if(!['адрес:','address:','adresse :','adresse:'].includes(txt))return;const address=el.textContent.replace(/^.*?:\s*/,'').trim();if(!address)return;el.dataset.address=address;el.classList.add('contact-actionable');el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',x.addressActions+' '+address)})}
  const sync=()=>mark(document);mark();window.syncContactActions=sync;
  document.addEventListener('click',e=>{const tel=e.target.closest('a[href^="tel:"]');if(tel){e.preventDefault();openMenu('phone',tel.getAttribute('href').slice(4),tel.textContent.trim(),tel.href);return}const mail=e.target.closest('a[href^="mailto:"]');if(mail){e.preventDefault();const value=mail.getAttribute('href').slice(7).split('?')[0];openMenu('email',value,mail.textContent.replace(/^✉️?\s*/,'').trim(),mail.href);return}const address=e.target.closest('[data-address]');if(address){openMenu('address',address.dataset.address,address.dataset.address);return}if(e.target===dialog){dialog.close();return}if(e.target.closest('.lang-option,#management-company,[data-action="management"],[data-action="services"],#passport-service,#elevator-service,#intercom-service,#spring-service,#video-service'))setTimeout(sync,40)});
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches?.('[data-address]')){e.preventDefault();const a=e.target;openMenu('address',a.dataset.address,a.dataset.address)}});
})();