(()=>{
  const tr={
    ru:{title:'Игры',sub:'Мини-игры для телефона',back:'← Назад к разделам',section:'Игры',hint:'Небольшие игры, которые работают прямо в браузере.',soon:'Скоро',play:'Играть',gameBack:'← К списку игр',newGame:'Новая игра',score:'Счёт',best:'Рекорд',how2048:'Свайпайте по полю, чтобы соединять одинаковые плитки.',won:'Вы собрали 2048!',gameOver:'Ходов больше нет',continue:'Продолжить',again:'Начать заново',board2048:'Игровое поле 2048',snakeHow:'Свайпайте по полю или используйте кнопки. Собирайте еду и не врезайтесь в себя.',snakeOver:'Игра окончена',snakeStart:'Старт',snakePause:'Пауза',snakeResume:'Продолжить',snakeBoard:'Игровое поле змейки',games:[['🧩','2048','Собирайте одинаковые плитки.'],['🐍','Змейка','Классическая змейка со свайпами.'],['🧠','Память','Находите одинаковые пары.'],['💣','Сапёр','Открывайте клетки и избегайте мин.'],['⭕','Крестики-нолики','Игра против компьютера.']]},
    en:{title:'Games',sub:'Mini games for your phone',back:'← Back to sections',section:'Games',hint:'Small games that run directly in the browser.',soon:'Soon',play:'Play',gameBack:'← Back to games',newGame:'New game',score:'Score',best:'Best',how2048:'Swipe the board to merge matching tiles.',won:'You made 2048!',gameOver:'No moves left',continue:'Continue',again:'Start again',board2048:'2048 game board',snakeHow:'Swipe the board or use the buttons. Eat food and avoid hitting yourself.',snakeOver:'Game over',snakeStart:'Start',snakePause:'Pause',snakeResume:'Resume',snakeBoard:'Snake game board',games:[['🧩','2048','Merge matching tiles.'],['🐍','Snake','Classic snake with swipe controls.'],['🧠','Memory','Find matching pairs.'],['💣','Minesweeper','Open cells and avoid mines.'],['⭕','Tic-tac-toe','Play against the computer.']]},
    fr:{title:'Jeux',sub:'Mini-jeux pour téléphone',back:'← Retour aux sections',section:'Jeux',hint:'De petits jeux qui fonctionnent directement dans le navigateur.',soon:'Bientôt',play:'Jouer',gameBack:'← Retour aux jeux',newGame:'Nouvelle partie',score:'Score',best:'Record',how2048:'Faites glisser le plateau pour fusionner les tuiles identiques.',won:'Vous avez obtenu 2048 !',gameOver:'Plus aucun coup possible',continue:'Continuer',again:'Recommencer',board2048:'Plateau de jeu 2048',snakeHow:'Faites glisser le plateau ou utilisez les boutons. Mangez la nourriture sans vous heurter.',snakeOver:'Partie terminée',snakeStart:'Démarrer',snakePause:'Pause',snakeResume:'Continuer',snakeBoard:'Plateau de Snake',games:[['🧩','2048','Fusionnez les tuiles identiques.'],['🐍','Snake','Le serpent classique avec des gestes.'],['🧠','Mémoire','Trouvez les paires identiques.'],['💣','Démineur','Ouvrez les cases et évitez les mines.'],['⭕','Morpion','Jouez contre l’ordinateur.']]},
    de:{title:'Spiele',sub:'Minispiele fürs Handy',back:'← Zurück zu den Bereichen',section:'Spiele',hint:'Kleine Spiele, die direkt im Browser laufen.',soon:'Bald',play:'Spielen',gameBack:'← Zurück zu den Spielen',newGame:'Neues Spiel',score:'Punkte',best:'Rekord',how2048:'Wischen Sie über das Feld, um gleiche Kacheln zusammenzuführen.',won:'2048 erreicht!',gameOver:'Keine Züge mehr möglich',continue:'Weiterspielen',again:'Neu starten',board2048:'2048-Spielfeld',snakeHow:'Wischen Sie über das Feld oder nutzen Sie die Tasten. Fressen Sie Futter und vermeiden Sie Kollisionen.',snakeOver:'Spiel beendet',snakeStart:'Start',snakePause:'Pause',snakeResume:'Weiter',snakeBoard:'Snake-Spielfeld',games:[['🧩','2048','Gleiche Kacheln zusammenführen.'],['🐍','Snake','Klassisches Snake mit Wischsteuerung.'],['🧠','Memory','Finde gleiche Paare.'],['💣','Minesweeper','Felder öffnen und Minen vermeiden.'],['⭕','Tic-Tac-Toe','Gegen den Computer spielen.']]}
  };
  const lang=()=>tr[document.documentElement.lang]?document.documentElement.lang:'ru';
  let nav,view,g2048,snakeView;

  const key='lugovoy-2048-state',bestKey='lugovoy-2048-best';
  let board=Array(16).fill(0),score=0,best=Number(localStorage.getItem(bestKey)||0),wonShown=false;

  let snake=[],food={x:0,y:0},dir={x:1,y:0},nextDir={x:1,y:0},snakeScore=0,snakeBest=Number(localStorage.getItem('lugovoy-snake-best')||0),snakeTimer=null,snakeRunning=false,snakeDead=false;
  const S=16;

  function build(){
    const grid=document.querySelector('.new-home-grid');nav=document.querySelector('.new-home-nav');const main=document.getElementById('top');if(!grid||!nav||!main)return;
    let button=grid.querySelector('[data-action="games"]');if(!button){button=document.createElement('button');button.type='button';button.className='new-home-card nav-games';button.dataset.action='games';button.innerHTML='<span class="nav-emoji">🎮</span><strong></strong><small></small>';grid.appendChild(button);}
    view=document.querySelector('.games-view');if(!view){view=document.createElement('section');view.className='games-view';view.hidden=true;view.innerHTML='<button type="button" class="games-back"></button><h2 class="games-title"></h2><p class="games-subtitle"></p><div class="games-grid"></div>';main.insertBefore(view,nav.nextSibling);view.querySelector('.games-back').addEventListener('click',showHome);}
    g2048=document.querySelector('.game2048-view');if(!g2048){g2048=document.createElement('section');g2048.className='game2048-view';g2048.hidden=true;g2048.innerHTML=`<button type="button" class="game2048-back"></button><div class="game2048-head"><div><h2>2048</h2><p class="game2048-help"></p></div><button type="button" class="game2048-new"></button></div><div class="game2048-scores"><div><span class="score-label"></span><strong id="score2048">0</strong></div><div><span class="best-label"></span><strong id="best2048">0</strong></div></div><div class="game2048-board" role="application" tabindex="0"><div class="game2048-cells"></div><div class="game2048-overlay" hidden><strong></strong><div><button type="button" class="game2048-continue"></button><button type="button" class="game2048-restart"></button></div></div></div>`;main.insertBefore(g2048,view.nextSibling);setup2048();}
    snakeView=document.querySelector('.snake-view');if(!snakeView){snakeView=document.createElement('section');snakeView.className='snake-view';snakeView.hidden=true;snakeView.innerHTML=`<button type="button" class="snake-back"></button><div class="snake-head"><div><h2>🐍 Snake</h2><p class="snake-help"></p></div><button type="button" class="snake-new"></button></div><div class="snake-scores"><div><span class="snake-score-label"></span><strong id="snake-score">0</strong></div><div><span class="snake-best-label"></span><strong id="snake-best">0</strong></div></div><div class="snake-board" tabindex="0" role="application"><canvas width="320" height="320"></canvas><div class="snake-overlay" hidden><strong></strong><button type="button" class="snake-restart"></button></div></div><div class="snake-controls"><button data-dir="up">↑</button><div><button data-dir="left">←</button><button class="snake-pause"></button><button data-dir="right">→</button></div><button data-dir="down">↓</button></div>`;main.insertBefore(snakeView,g2048.nextSibling);setupSnake();}
    button.addEventListener('click',e=>{e.stopPropagation();showGames();});
    view.addEventListener('click',e=>{const card=e.target.closest('[data-game]');if(card?.dataset.game==='2048')show2048();if(card?.dataset.game==='snake')showSnake();});
    load2048();resetSnake(false);apply();render2048();renderSnake();
  }

  function hideAll(){nav.hidden=true;view.hidden=true;g2048.hidden=true;snakeView.hidden=true;document.querySelector('.new-ui-search-view')?.setAttribute('hidden','');}
  function showHome(){stopSnake();view.hidden=true;g2048.hidden=true;snakeView.hidden=true;nav.hidden=false;nav.scrollIntoView({behavior:'smooth',block:'start'});}
  function showGames(){stopSnake();hideAll();view.hidden=false;view.scrollIntoView({behavior:'smooth',block:'start'});}
  function show2048(){stopSnake();hideAll();g2048.hidden=false;g2048.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>g2048.querySelector('.game2048-board')?.focus({preventScroll:true}),150);render2048();}
  function showSnake(){hideAll();snakeView.hidden=false;snakeView.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>snakeView.querySelector('.snake-board')?.focus({preventScroll:true}),150);renderSnake();}

  function setup2048(){g2048.querySelector('.game2048-back').addEventListener('click',showGames);g2048.querySelector('.game2048-new').addEventListener('click',new2048);g2048.querySelector('.game2048-restart').addEventListener('click',new2048);g2048.querySelector('.game2048-continue').addEventListener('click',()=>{wonShown=true;hide2048Overlay();save2048();});const b=g2048.querySelector('.game2048-board');let sx=0,sy=0;b.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture?.(e.pointerId)});b.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;move2048(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));});b.addEventListener('keydown',e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(d[e.key]){e.preventDefault();move2048(d[e.key]);}});}
  function new2048(){board=Array(16).fill(0);score=0;wonShown=false;add2048();add2048();hide2048Overlay();save2048();render2048();}
  function add2048(){const e=[];board.forEach((v,i)=>{if(!v)e.push(i)});if(e.length){const i=e[Math.floor(Math.random()*e.length)];board[i]=Math.random()<.9?2:4;}}
  function collapse(line){const vals=line.filter(Boolean),out=[];let pts=0;for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){const v=vals[i]*2;out.push(v);pts+=v;i++;}else out.push(vals[i]);}while(out.length<4)out.push(0);return [out,pts];}
  function move2048(d){const old=board.slice();let pts=0,next=Array(16).fill(0);for(let n=0;n<4;n++){let line=[];if(d==='left'||d==='right')for(let c=0;c<4;c++)line.push(board[n*4+c]);else for(let r=0;r<4;r++)line.push(board[r*4+n]);if(d==='right'||d==='down')line.reverse();let r,g;[r,g]=collapse(line);pts+=g;if(d==='right'||d==='down')r.reverse();if(d==='left'||d==='right')for(let c=0;c<4;c++)next[n*4+c]=r[c];else for(let rr=0;rr<4;rr++)next[rr*4+n]=r[rr];}if(old.every((v,i)=>v===next[i]))return;board=next;score+=pts;if(score>best){best=score;localStorage.setItem(bestKey,String(best));}add2048();save2048();render2048();if(!wonShown&&board.some(v=>v>=2048))show2048Overlay('won');else if(!has2048Moves())show2048Overlay('over');}
  function has2048Moves(){if(board.some(v=>!v))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const v=board[r*4+c];if(c<3&&v===board[r*4+c+1])return true;if(r<3&&v===board[(r+1)*4+c])return true;}return false;}
  function save2048(){localStorage.setItem(key,JSON.stringify({board,score,wonShown}));}
  function load2048(){try{const s=JSON.parse(localStorage.getItem(key));if(Array.isArray(s?.board)&&s.board.length===16){board=s.board.map(Number);score=Number(s.score)||0;wonShown=!!s.wonShown;if(board.some(Boolean))return;}}catch{}new2048();}
  function show2048Overlay(type){const t=tr[lang()],o=g2048.querySelector('.game2048-overlay');o.hidden=false;o.dataset.type=type;o.querySelector('strong').textContent=type==='won'?t.won:t.gameOver;o.querySelector('.game2048-continue').hidden=type!=='won';}
  function hide2048Overlay(){const o=g2048?.querySelector('.game2048-overlay');if(o)o.hidden=true;}
  function render2048(){if(!g2048)return;g2048.querySelector('.game2048-cells').innerHTML=board.map(v=>`<div class="tile2048${v?' has-value':''}" data-value="${v||0}">${v||''}</div>`).join('');g2048.querySelector('#score2048').textContent=score;g2048.querySelector('#best2048').textContent=best;}

  function setupSnake(){snakeView.querySelector('.snake-back').addEventListener('click',showGames);snakeView.querySelector('.snake-new').addEventListener('click',()=>resetSnake(true));snakeView.querySelector('.snake-restart').addEventListener('click',()=>resetSnake(true));snakeView.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('click',()=>setSnakeDir(b.dataset.dir)));snakeView.querySelector('.snake-pause').addEventListener('click',toggleSnake);const b=snakeView.querySelector('.snake-board');let sx=0,sy=0;b.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture?.(e.pointerId)});b.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<22)return;setSnakeDir(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));if(!snakeRunning&&!snakeDead)startSnake();});b.addEventListener('keydown',e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(d[e.key]){e.preventDefault();setSnakeDir(d[e.key]);if(!snakeRunning&&!snakeDead)startSnake();}if(e.key===' '){e.preventDefault();toggleSnake();}});}
  function resetSnake(start){stopSnake();snake=[{x:7,y:8},{x:6,y:8},{x:5,y:8}];dir={x:1,y:0};nextDir={x:1,y:0};snakeScore=0;snakeDead=false;placeFood();snakeView.querySelector('.snake-overlay').hidden=true;renderSnake();if(start)startSnake();}
  function placeFood(){const free=[];for(let y=0;y<S;y++)for(let x=0;x<S;x++)if(!snake.some(p=>p.x===x&&p.y===y))free.push({x,y});food=free[Math.floor(Math.random()*free.length)]||{x:0,y:0};}
  function setSnakeDir(d){const m={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}}[d];if(!m)return;if(m.x===-dir.x&&m.y===-dir.y)return;nextDir=m;}
  function startSnake(){if(snakeRunning||snakeDead)return;snakeRunning=true;snakeTimer=setInterval(tickSnake,135);apply();}
  function stopSnake(){if(snakeTimer)clearInterval(snakeTimer);snakeTimer=null;snakeRunning=false;if(snakeView)apply();}
  function toggleSnake(){if(snakeDead){resetSnake(true);return;}if(snakeRunning)stopSnake();else startSnake();}
  function tickSnake(){dir=nextDir;const h=snake[0],n={x:h.x+dir.x,y:h.y+dir.y};if(n.x<0||n.y<0||n.x>=S||n.y>=S||snake.some(p=>p.x===n.x&&p.y===n.y)){snakeDead=true;stopSnake();if(snakeScore>snakeBest){snakeBest=snakeScore;localStorage.setItem('lugovoy-snake-best',String(snakeBest));}const o=snakeView.querySelector('.snake-overlay');o.hidden=false;o.querySelector('strong').textContent=tr[lang()].snakeOver;renderSnake();return;}snake.unshift(n);if(n.x===food.x&&n.y===food.y){snakeScore++;if(snakeScore>snakeBest){snakeBest=snakeScore;localStorage.setItem('lugovoy-snake-best',String(snakeBest));}placeFood();}else snake.pop();renderSnake();}
  function renderSnake(){if(!snakeView)return;const c=snakeView.querySelector('canvas'),ctx=c.getContext('2d'),cell=c.width/S;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#dfe9e5';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='rgba(23,49,63,.08)';for(let i=1;i<S;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,c.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*cell);ctx.lineTo(c.width,i*cell);ctx.stroke();}ctx.fillStyle='#ef5350';ctx.beginPath();ctx.arc((food.x+.5)*cell,(food.y+.5)*cell,cell*.32,0,Math.PI*2);ctx.fill();snake.forEach((p,i)=>{ctx.fillStyle=i===0?'#126e65':'#2bb673';ctx.fillRect(p.x*cell+2,p.y*cell+2,cell-4,cell-4);});snakeView.querySelector('#snake-score').textContent=snakeScore;snakeView.querySelector('#snake-best').textContent=snakeBest;}

  function apply(){const t=tr[lang()],button=document.querySelector('[data-action="games"]');if(button){button.querySelector('strong').textContent=t.title;button.querySelector('small').textContent=t.sub;}if(view){view.querySelector('.games-back').textContent=t.back;view.querySelector('.games-title').textContent=t.section;view.querySelector('.games-subtitle').textContent=t.hint;view.querySelector('.games-grid').innerHTML=t.games.map((g,i)=>`<button type="button" class="game-card${i<2?' game-ready':''}" ${i===0?'data-game="2048"':i===1?'data-game="snake"':''}><span class="game-icon" aria-hidden="true">${g[0]}</span><span><strong>${g[1]}</strong><small>${g[2]}</small><span class="game-soon">${i<2?t.play:t.soon}</span></span></button>`).join('');}if(g2048){g2048.querySelector('.game2048-back').textContent=t.gameBack;g2048.querySelector('.game2048-new').textContent=t.newGame;g2048.querySelector('.game2048-help').textContent=t.how2048;g2048.querySelector('.score-label').textContent=t.score;g2048.querySelector('.best-label').textContent=t.best;g2048.querySelector('.game2048-board').setAttribute('aria-label',t.board2048);g2048.querySelector('.game2048-continue').textContent=t.continue;g2048.querySelector('.game2048-restart').textContent=t.again;const o=g2048.querySelector('.game2048-overlay');if(!o.hidden)show2048Overlay(o.dataset.type||'over');}if(snakeView){snakeView.querySelector('.snake-back').textContent=t.gameBack;snakeView.querySelector('.snake-new').textContent=t.newGame;snakeView.querySelector('.snake-help').textContent=t.snakeHow;snakeView.querySelector('.snake-score-label').textContent=t.score;snakeView.querySelector('.snake-best-label').textContent=t.best;snakeView.querySelector('.snake-board').setAttribute('aria-label',t.snakeBoard);snakeView.querySelector('.snake-pause').textContent=snakeDead?t.snakeStart:(snakeRunning?t.snakePause:t.snakeResume);snakeView.querySelector('.snake-restart').textContent=t.again;const o=snakeView.querySelector('.snake-overlay');if(!o.hidden)o.querySelector('strong').textContent=t.snakeOver;}}
  new MutationObserver(()=>requestAnimationFrame(apply)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();