(()=>{
  const langs=['ru','en','fr','de'];
  const lang=()=>langs.includes(document.documentElement.lang)?document.documentElement.lang:'ru';
  const rows=[
    ['Позвонить','Call','Appeler','Anrufen'],['Пн–Чт:','Mon–Thu:','Lun–Jeu :','Mo–Do:'],['Пт:','Fri:','Ven :','Fr:'],['Обед:','Lunch:','Pause :','Pause:'],['Сб, Вс:','Sat, Sun:','Sam., dim. :','Sa, So:'],['выходные','closed','fermé','geschlossen'],
    ['Бухгалтерия','Accounting','Comptabilité','Buchhaltung'],['Паспортный стол','Registration office','Bureau d’enregistrement','Meldebüro'],['Юридический отдел по взысканию задолженности','Legal debt collection','Service juridique du recouvrement','Rechtsabteilung Forderungseinzug'],['Режим работы офисов','Office hours','Horaires des bureaux','Bürozeiten'],
    ['Обслуживающие организации','Service organizations','Organismes de service','Dienstleister'],['Контактная информация','Contact information','Coordonnées','Kontaktinformationen'],['Обслуживание лифтов','Elevator service','Entretien des ascenseurs','Aufzugsservice'],['📞 Диспетчер','📞 Dispatcher','📞 Répartiteur','📞 Leitstelle'],['🚨 Аварийная служба','🚨 Emergency service','🚨 Service d’urgence','🚨 Notdienst'],['📋 Инструкция и правила пользования','📋 Instructions and rules of use','📋 Instructions et règles d’utilisation','📋 Anleitung und Nutzungsregeln'],['⛔ Запрещается','⛔ Prohibited','⛔ Interdit','⛔ Verboten'],
    ['Для вызова кабины нажмите кнопку у входа в лифт.','Press the call button at the elevator entrance to call the car.','Appuyez sur le bouton d’appel à l’entrée de l’ascenseur.','Drücken Sie zum Rufen der Kabine die Ruftaste am Aufzugseingang.'],['Двери кабины открываются автоматически. После открытия дверей убедитесь, что кабина находится перед Вами.','The doors open automatically. After they open, make sure the elevator car is in front of you.','Les portes s’ouvrent automatiquement. Après ouverture, vérifiez que la cabine est bien devant vous.','Die Türen öffnen automatisch. Vergewissern Sie sich, dass sich die Kabine vor Ihnen befindet.'],['Войдя в кабину, нажмите кнопку нужного Вам этажа.','After entering, press the button for the required floor.','Dans la cabine, appuyez sur le bouton de l’étage souhaité.','Drücken Sie in der Kabine die Taste des gewünschten Stockwerks.'],['Для быстрого закрытия дверей нажмите кнопку закрытия дверей.','Use the door-close button to close the doors sooner.','Pour fermer les portes plus rapidement, appuyez sur le bouton de fermeture.','Zum schnelleren Schließen drücken Sie die Tür-schließen-Taste.'],['Для повторного открытия дверей нажмите кнопку открытия дверей.','Use the door-open button to reopen the doors.','Pour rouvrir les portes, appuyez sur le bouton d’ouverture.','Zum erneuten Öffnen drücken Sie die Tür-öffnen-Taste.'],
    ['Домофон','Intercom','Interphone','Gegensprechanlage'],['📱 Регистрация в приложении «Наш дом»','📱 Registration in the “Nash Dom” app','📱 Inscription dans l’application « Nash Dom »','📱 Registrierung in der App „Nash Dom“'],['Скачать приложение:','Download the app:','Télécharger l’application :','App herunterladen:'],['🔔 Как включить звонки в приложении','🔔 How to enable calls in the app','🔔 Activer les appels dans l’application','🔔 Anrufe in der App aktivieren'],['Видеонаблюдение','Video surveillance','Vidéosurveillance','Videoüberwachung'],['Домашний родник','Home Spring','Source domestique','Hausquelle']
  ];
  const map=new Map();for(const r of rows)for(const v of r)map.set(v.trim(),r);
  function apply(root){if(!root)return;const i=langs.indexOf(lang());const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||p.tagName==='SCRIPT'||p.tagName==='STYLE'||p.tagName==='PRE')return NodeFilter.FILTER_REJECT;return n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){const k=n.nodeValue.trim(),r=map.get(k);if(r){const a=n.nodeValue.match(/^\s*/)?.[0]||'',b=n.nodeValue.match(/\s*$/)?.[0]||'';n.nodeValue=a+r[i]+b}}document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.dataset.callLabel={ru:'Позвонить',en:'Call',fr:'Appeler',de:'Anrufen'}[lang()]);}
  function openDialogs(){document.querySelectorAll('dialog[open]').forEach(apply)}
  new MutationObserver(()=>{requestAnimationFrame(()=>{openDialogs();})}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  document.addEventListener('click',e=>{if(e.target.closest('#about,[data-action="management"],[data-action="services"],#passport-service,#elevator-service,#intercom-service,#spring-service,#video-service,.lang-option'))setTimeout(openDialogs,30)});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply(document));else apply(document);
})();