(()=>{
  const langs=['ru','en','fr','de'];
  const lang=()=>langs.includes(document.documentElement.lang)?document.documentElement.lang:'ru';
  const rows=[
    ['Позвонить','Call','Appeler','Anrufen'],['Пн–Чт:','Mon–Thu:','Lun–Jeu :','Mo–Do:'],['Пт:','Fri:','Ven :','Fr:'],['Обед:','Lunch:','Pause :','Pause:'],['Сб, Вс:','Sat, Sun:','Sam., dim. :','Sa, So:'],['выходные','closed','fermé','geschlossen'],
    ['Бухгалтерия','Accounting','Comptabilité','Buchhaltung'],['Паспортный стол','Registration office','Bureau d’enregistrement','Meldebüro'],['Юридический отдел по взысканию задолженности','Legal debt collection','Service juridique du recouvrement','Rechtsabteilung Forderungseinzug'],['Режим работы офисов','Office hours','Horaires des bureaux','Bürozeiten'],
    ['Обслуживающие организации','Service organizations','Organismes de service','Dienstleister'],['Контактная информация','Contact information','Coordonnées','Kontaktinformationen'],['Обслуживание лифтов','Elevator service','Entretien des ascenseurs','Aufzugsservice'],['📞 Диспетчер','📞 Dispatcher','📞 Répartiteur','📞 Leitstelle'],['🚨 Аварийная служба','🚨 Emergency service','🚨 Service d’urgence','🚨 Notdienst'],['📋 Инструкция и правила пользования','📋 Instructions and rules of use','📋 Instructions et règles d’utilisation','📋 Anleitung und Nutzungsregeln'],['Специализированная лифтовая организация:','Specialized elevator service company:','Entreprise spécialisée dans les ascenseurs :','Spezialisiertes Aufzugsunternehmen:'],['⛔ Запрещается','⛔ Prohibited','⛔ Interdit','⛔ Verboten'],
    ['Для вызова кабины нажмите кнопку у входа в лифт.','Press the call button at the elevator entrance to call the car.','Appuyez sur le bouton d’appel à l’entrée de l’ascenseur.','Drücken Sie zum Rufen der Kabine die Ruftaste am Aufzugseingang.'],
    ['Двери кабины открываются автоматически. После открытия дверей убедитесь, что кабина находится перед Вами.','The doors open automatically. After they open, make sure the elevator car is in front of you.','Les portes s’ouvrent automatiquement. Après ouverture, vérifiez que la cabine est bien devant vous.','Die Türen öffnen automatisch. Vergewissern Sie sich, dass sich die Kabine vor Ihnen befindet.'],
    ['При входе в кабину с ребенком войдите первыми, при выходе — пропустите ребенка вперед. Если ребенок в коляске, то при входе и выходе из лифта держите ребенка на руках.','When entering with a child, enter first; when exiting, let the child go first. If the child is in a stroller, hold the child in your arms when entering and leaving the elevator.','Avec un enfant, entrez en premier et laissez l’enfant sortir en premier. Si l’enfant est en poussette, tenez-le dans vos bras lors de l’entrée et de la sortie de l’ascenseur.','Mit einem Kind betreten Sie die Kabine zuerst; beim Aussteigen lassen Sie das Kind zuerst gehen. Befindet sich das Kind in einem Kinderwagen, halten Sie es beim Ein- und Aussteigen auf dem Arm.'],
    ['Войдя в кабину, нажмите кнопку нужного Вам этажа.','After entering, press the button for the required floor.','Dans la cabine, appuyez sur le bouton de l’étage souhaité.','Drücken Sie in der Kabine die Taste des gewünschten Stockwerks.'],
    ['Для быстрого закрытия дверей нажмите кнопку закрытия дверей.','Use the door-close button to close the doors sooner.','Pour fermer les portes plus rapidement, appuyez sur le bouton de fermeture.','Zum schnelleren Schließen drücken Sie die Tür-schließen-Taste.'],
    ['Для повторного открытия дверей нажмите кнопку открытия дверей.','Use the door-open button to reopen the doors.','Pour rouvrir les portes, appuyez sur le bouton d’ouverture.','Zum erneuten Öffnen drücken Sie die Tür-öffnen-Taste.'],
    ['При неисправности лифта нажмите и удерживайте кнопку вызова диспетчера до ответа автоинформатора. Дождитесь ответа диспетчера, затем сообщите о случившемся и выполняйте его рекомендации.','If the elevator malfunctions, press and hold the dispatcher call button until the automated message responds. Wait for the dispatcher, explain what happened and follow their instructions.','En cas de panne de l’ascenseur, maintenez le bouton d’appel du répartiteur jusqu’à la réponse du message automatique. Attendez le répartiteur, expliquez la situation et suivez ses instructions.','Bei einer Störung halten Sie die Ruftaste zur Leitstelle gedrückt, bis die automatische Ansage reagiert. Warten Sie auf die Leitstelle, schildern Sie den Vorfall und folgen Sie den Anweisungen.'],
    ['Внимание:','Warning:','Attention :','Achtung:'],
    ['при возникновении пожара в здании лифт будет принудительно направлен на основной посадочный этаж. По прибытии кабины на этот этаж необходимо покинуть кабину и выйти из здания. Использование лифта во время пожара не допускается.','if a fire occurs in the building, the elevator will automatically be sent to the main landing floor. When it arrives, leave the car and exit the building. Do not use the elevator during a fire.','en cas d’incendie dans le bâtiment, l’ascenseur sera automatiquement dirigé vers l’étage principal. À son arrivée, quittez la cabine et sortez du bâtiment. L’utilisation de l’ascenseur pendant un incendie est interdite.','bei einem Brand im Gebäude wird der Aufzug automatisch in das Hauptzugangsgeschoss gefahren. Verlassen Sie dort die Kabine und das Gebäude. Die Benutzung des Aufzugs während eines Brandes ist verboten.'],
    ['Самостоятельная эвакуация из неисправного лифта.','Attempting to evacuate yourself from a faulty elevator.','Évacuation autonome depuis un ascenseur en panne.','Eigenständige Evakuierung aus einem defekten Aufzug.'],
    ['Курение, перевозка легковоспламеняющихся и взрывчатых веществ.','Smoking or transporting flammable or explosive substances.','Fumer ou transporter des substances inflammables ou explosives.','Rauchen sowie Transport entzündlicher oder explosiver Stoffe.'],
    ['Открывание дверей вручную и задержка их закрытия.','Opening the doors manually or preventing them from closing.','Ouvrir les portes manuellement ou empêcher leur fermeture.','Manuelles Öffnen der Türen oder Verhindern des Schließens.'],
    ['Перегрузка кабины и перевозка крупногабаритных грузов.','Overloading the car or transporting oversized loads.','Surcharger la cabine ou transporter des charges surdimensionnées.','Überladen der Kabine oder Transport übergroßer Lasten.'],
    ['Проезд детей дошкольного возраста без сопровождения взрослых.','Allowing preschool children to ride without an adult.','Laisser des enfants d’âge préscolaire voyager sans adulte.','Fahrt von Vorschulkindern ohne Begleitung Erwachsener.'],
    ['Использование лифта во время пожарной тревоги.','Using the elevator during a fire alarm.','Utiliser l’ascenseur pendant une alarme incendie.','Benutzung des Aufzugs während eines Feueralarms.'],
    ['Домофон','Intercom','Interphone','Gegensprechanlage'],['📱 Регистрация в приложении «Наш дом»','📱 Registration in the “Nash Dom” app','📱 Inscription dans l’application « Nash Dom »','📱 Registrierung in der App „Nash Dom“'],['Скачать приложение:','Download the app:','Télécharger l’application :','App herunterladen:'],['🔔 Как включить звонки в приложении','🔔 How to enable calls in the app','🔔 Activer les appels dans l’application','🔔 Anrufe in der App aktivieren'],['Видеонаблюдение','Video surveillance','Vidéosurveillance','Videoüberwachung'],['Домашний родник','Home Spring','Source domestique','Hausquelle']
  ];
  const map=new Map();for(const r of rows)for(const v of r)map.set(v.trim(),r);
  function apply(root){if(!root)return;const i=langs.indexOf(lang());const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||p.tagName==='SCRIPT'||p.tagName==='STYLE'||p.tagName==='PRE')return NodeFilter.FILTER_REJECT;return n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){const k=n.nodeValue.trim(),r=map.get(k);if(r){const a=n.nodeValue.match(/^\s*/)?.[0]||'',b=n.nodeValue.match(/\s*$/)?.[0]||'';n.nodeValue=a+r[i]+b}}document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.dataset.callLabel={ru:'Позвонить',en:'Call',fr:'Appeler',de:'Anrufen'}[lang()]);}
  function openDialogs(){document.querySelectorAll('dialog[open]').forEach(apply)}
  new MutationObserver(()=>requestAnimationFrame(openDialogs)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  document.addEventListener('click',e=>{if(e.target.closest('#about,[data-action="management"],[data-action="services"],#passport-service,#elevator-service,#intercom-service,#spring-service,#video-service,.lang-option'))setTimeout(openDialogs,30)});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply(document));else apply(document);
})();