(()=>{
  const T={
    ru:{title:'Память',back:'← К списку игр',newGame:'Новая игра',moves:'Ходы',pairs:'Пары',best:'Рекорд',hint:'Открывайте по две карточки и находите одинаковые пары.',win:'Все пары найдены!',again:'Играть ещё',card:'Карточка',play:'Играть'},
    en:{title:'Memory',back:'← Back to games',newGame:'New game',moves:'Moves',pairs:'Pairs',best:'Best',hint:'Open two cards at a time and find matching pairs.',win:'All pairs found!',again:'Play again',card:'Card',play:'Play'},
    fr:{title:'Mémoire',back:'← Retour aux jeux',newGame:'Nouvelle partie',moves:'Coups',pairs:'Paires',best:'Record',hint:'Retournez deux cartes et trouvez les paires identiques.',win:'Toutes les paires sont trouvées !',again:'Rejouer',card:'Carte',play:'Jouer'},
    de:{title:'Memory',back:'← Zurück zu den Spielen',newGame:'Neues Spiel',moves:'Züge',pairs:'Paare',best:'Rekord',hint:'Decken Sie jeweils zwei Karten auf und finden Sie gleiche Paare.',win:'Alle Paare gefunden!',again:'Noch einmal',card:'Karte',play:'Spielen'}
  };
  const L=()=>T[document.documentElement.lang]?document.documentElement.lang:'ru';
  const symbols=['🐶','🐱','🦊','🐼','🐸','🐵','🦁','🐯'];
  let view=null,cards=[],open=[],matched=new Set(),moves=0,locked=false;
  let best=Number(localStorage.getItem('lugovoy-memory-best')||0);

  const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
  function newGame(){cards=shuffle([...symbols,...symbols].map((v,i)=>({id:i,value:v})));open=[];matched.clear();moves=0;locked=false;view.querySelector('.memory-overlay').hidden=true;render();}
  function choose(i){if(locked||matched.has(i)||open.includes(i))return;open.push(i);render();if(open.length<2)return;moves++;const [a,b]=open;if(cards[a].value===cards[b].value){matched.add(a);matched.add(b);open=[];render();if(matched.size===cards.length)finish();}else{locked=true;setTimeout(()=>{open=[];locked=false;render();},650);}}
  function finish(){if(!best||moves<best){best=moves;localStorage.setItem('lugovoy-memory-best',String(best));}renderStats();const o=view.querySelector('.memory-overlay');o.hidden=false;o.querySelector('strong').textContent=T[L()].win;}
  function renderStats(){if(!view)return;view.querySelector('[data-memory-moves]').textContent=moves;view.querySelector('[data-memory-pairs]').textContent=`${matched.size/2}/8`;view.querySelector('[data-memory-best]').textContent=best||'—';}
  function render(){if(!view)return;const t=T[L()];const board=view.querySelector('.memory-board');board.innerHTML=cards.map((c,i)=>{const shown=open.includes(i)||matched.has(i);return `<button type="button" class="memory-card${shown?' is-open':''}${matched.has(i)?' is-matched':''}" data-memory-card="${i}" aria-label="${t.card} ${i+1}"><span>${shown?c.value:'?'}</span></button>`}).join('');renderStats();}
  function decorateCard(){const card=document.querySelectorAll('.games-grid .game-card')[2];if(!card)return;card.classList.add('game-ready');card.dataset.game='memory';const badge=card.querySelector('.game-soon');if(badge)badge.textContent=T[L()].play;}
  function hideOthers(){document.querySelector('.new-home-nav')?.setAttribute('hidden','');document.querySelector('.games-view')?.setAttribute('hidden','');document.querySelector('.game2048-view')?.setAttribute('hidden','');document.querySelector('.snake-view')?.setAttribute('hidden','');document.querySelector('.tictactoe-view')?.setAttribute('hidden','');document.querySelector('.new-ui-search-view')?.setAttribute('hidden','');}
  function showGame(){hideOthers();view.hidden=false;view.scrollIntoView({behavior:'smooth',block:'start'});}
  function showGames(){view.hidden=true;const games=document.querySelector('.games-view');if(games){games.hidden=false;decorateCard();games.scrollIntoView({behavior:'smooth',block:'start'});}}
  function apply(){if(!view)return;const t=T[L()];view.querySelector('h2').textContent=`🧠 ${t.title}`;view.querySelector('.memory-back').textContent=t.back;view.querySelector('.memory-new').textContent=t.newGame;view.querySelector('.memory-help').textContent=t.hint;view.querySelector('.memory-moves-label').textContent=t.moves;view.querySelector('.memory-pairs-label').textContent=t.pairs;view.querySelector('.memory-best-label').textContent=t.best;view.querySelector('.memory-restart').textContent=t.again;decorateCard();render();}
  function build(){const main=document.getElementById('top');if(!main)return;view=document.querySelector('.memory-view');if(!view){view=document.createElement('section');view.className='memory-view';view.hidden=true;view.innerHTML=`<button type="button" class="memory-back"></button><div class="memory-head"><div><h2></h2><p class="memory-help"></p></div><button type="button" class="memory-new"></button></div><div class="memory-stats"><div><span class="memory-moves-label"></span><strong data-memory-moves>0</strong></div><div><span class="memory-pairs-label"></span><strong data-memory-pairs>0/8</strong></div><div><span class="memory-best-label"></span><strong data-memory-best>—</strong></div></div><div class="memory-wrap"><div class="memory-board"></div><div class="memory-overlay" hidden><strong></strong><button type="button" class="memory-restart"></button></div></div>`;main.appendChild(view);view.querySelector('.memory-back').addEventListener('click',showGames);view.querySelector('.memory-new').addEventListener('click',newGame);view.querySelector('.memory-restart').addEventListener('click',newGame);view.querySelector('.memory-board').addEventListener('click',e=>{const c=e.target.closest('[data-memory-card]');if(c)choose(Number(c.dataset.memoryCard));});}
    document.addEventListener('click',e=>{const card=e.target.closest('.games-grid .game-card');if(!card)return;const all=[...document.querySelectorAll('.games-grid .game-card')];if(card.dataset.game==='memory'||all.indexOf(card)===2){e.preventDefault();e.stopPropagation();decorateCard();showGame();}},true);
    newGame();apply();
  }
  new MutationObserver(()=>requestAnimationFrame(apply)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(build,0));else setTimeout(build,0);
})();