(()=>{
  const T={
    ru:{title:'Сапёр',back:'← К списку игр',newGame:'Новая игра',mines:'Мины',time:'Время',flags:'Флаги',hint:'Открывайте клетки и не попадите на мину. Для флага включите режим «Флаг» или удерживайте клетку.',flagMode:'🚩 Флаг',openMode:'👆 Открывать',win:'Поле очищено!',lose:'Вы попали на мину',again:'Играть ещё',cell:'Клетка',play:'Играть'},
    en:{title:'Minesweeper',back:'← Back to games',newGame:'New game',mines:'Mines',time:'Time',flags:'Flags',hint:'Open cells without hitting a mine. Use Flag mode or press and hold a cell to place a flag.',flagMode:'🚩 Flag',openMode:'👆 Open',win:'Board cleared!',lose:'You hit a mine',again:'Play again',cell:'Cell',play:'Play'},
    fr:{title:'Démineur',back:'← Retour aux jeux',newGame:'Nouvelle partie',mines:'Mines',time:'Temps',flags:'Drapeaux',hint:'Ouvrez les cases sans toucher une mine. Activez le mode drapeau ou maintenez une case.',flagMode:'🚩 Drapeau',openMode:'👆 Ouvrir',win:'Champ déminé !',lose:'Vous avez touché une mine',again:'Rejouer',cell:'Case',play:'Jouer'},
    de:{title:'Minesweeper',back:'← Zurück zu den Spielen',newGame:'Neues Spiel',mines:'Minen',time:'Zeit',flags:'Flaggen',hint:'Öffnen Sie Felder, ohne eine Mine zu treffen. Nutzen Sie den Flaggenmodus oder halten Sie ein Feld gedrückt.',flagMode:'🚩 Flagge',openMode:'👆 Öffnen',win:'Feld geräumt!',lose:'Mine getroffen',again:'Noch einmal',cell:'Feld',play:'Spielen'}
  };
  const L=()=>T[document.documentElement.lang]?document.documentElement.lang:'ru';
  const W=9,H=9,M=10;
  let view=null,cells=[],started=false,finished=false,flagMode=false,startAt=0,timer=null,elapsed=0;

  const index=(x,y)=>y*W+x;
  const neighbors=i=>{const x=i%W,y=Math.floor(i/W),out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<W&&ny<H)out.push(index(nx,ny));}return out;};
  function emptyBoard(){cells=Array.from({length:W*H},()=>({mine:false,open:false,flag:false,n:0}));}
  function placeMines(safe){const forbidden=new Set([safe,...neighbors(safe)]),pool=[];for(let i=0;i<cells.length;i++)if(!forbidden.has(i))pool.push(i);for(let n=0;n<M;n++){const p=Math.floor(Math.random()*pool.length),i=pool.splice(p,1)[0];cells[i].mine=true;}cells.forEach((c,i)=>{if(!c.mine)c.n=neighbors(i).filter(j=>cells[j].mine).length;});}
  function start(i){if(started)return;started=true;placeMines(i);startAt=Date.now();timer=setInterval(()=>{elapsed=Math.floor((Date.now()-startAt)/1000);renderStats();},1000);}
  function stopTimer(){if(timer)clearInterval(timer);timer=null;}
  function newGame(){stopTimer();emptyBoard();started=false;finished=false;flagMode=false;elapsed=0;if(view){view.querySelector('.mines-overlay').hidden=true;render();apply();}}
  function toggleFlag(i){if(finished||cells[i].open)return;cells[i].flag=!cells[i].flag;render();}
  function flood(i){const stack=[i],seen=new Set();while(stack.length){const k=stack.pop();if(seen.has(k))continue;seen.add(k);const c=cells[k];if(c.flag||c.open||c.mine)continue;c.open=true;if(c.n===0)neighbors(k).forEach(n=>{if(!seen.has(n)&&!cells[n].mine)stack.push(n);});}}
  function openCell(i){if(finished||cells[i].flag||cells[i].open)return;start(i);const c=cells[i];if(c.mine){c.open=true;finish(false);return;}flood(i);render();if(cells.filter(c=>c.open&&!c.mine).length===W*H-M)finish(true);}
  function finish(win){finished=true;stopTimer();if(win)cells.forEach(c=>{if(c.mine)c.flag=true;});else cells.forEach(c=>{if(c.mine)c.open=true;});render();const o=view.querySelector('.mines-overlay'),t=T[L()];o.hidden=false;o.querySelector('strong').textContent=win?t.win:t.lose;}
  function flags(){return cells.filter(c=>c.flag).length;}
  function renderStats(){if(!view)return;view.querySelector('[data-mines-left]').textContent=Math.max(0,M-flags());view.querySelector('[data-mines-time]').textContent=elapsed;view.querySelector('[data-mines-flags]').textContent=flags();}
  function render(){if(!view)return;const t=T[L()],b=view.querySelector('.mines-board');b.innerHTML=cells.map((c,i)=>{let text='';if(c.flag&&!c.open)text='🚩';else if(c.open&&c.mine)text='💣';else if(c.open&&c.n)text=String(c.n);const state=c.open?' is-open':'';return `<button type="button" class="mine-cell${state}${c.mine&&c.open?' is-mine':''}" data-mine-cell="${i}" data-number="${c.open&&!c.mine?c.n:0}" aria-label="${t.cell} ${i+1}">${text}</button>`;}).join('');renderStats();}
  function decorateCard(){const card=document.querySelectorAll('.games-grid .game-card')[3];if(!card)return;card.classList.add('game-ready');card.dataset.game='minesweeper';const badge=card.querySelector('.game-soon');if(badge)badge.textContent=T[L()].play;}
  function hideOthers(){document.querySelector('.new-home-nav')?.setAttribute('hidden','');document.querySelector('.games-view')?.setAttribute('hidden','');document.querySelector('.game2048-view')?.setAttribute('hidden','');document.querySelector('.snake-view')?.setAttribute('hidden','');document.querySelector('.memory-view')?.setAttribute('hidden','');document.querySelector('.tictactoe-view')?.setAttribute('hidden','');document.querySelector('.new-ui-search-view')?.setAttribute('hidden','');}
  function showGame(){hideOthers();view.hidden=false;decorateCard();view.scrollIntoView({behavior:'smooth',block:'start'});}
  function showGames(){view.hidden=true;const games=document.querySelector('.games-view');if(games){games.hidden=false;decorateCard();games.scrollIntoView({behavior:'smooth',block:'start'});}}
  function apply(){if(!view)return;const t=T[L()];view.querySelector('h2').textContent=`💣 ${t.title}`;view.querySelector('.mines-back').textContent=t.back;view.querySelector('.mines-new').textContent=t.newGame;view.querySelector('.mines-help').textContent=t.hint;view.querySelector('.mines-left-label').textContent=t.mines;view.querySelector('.mines-time-label').textContent=t.time;view.querySelector('.mines-flags-label').textContent=t.flags;view.querySelector('.mines-mode').textContent=flagMode?t.openMode:t.flagMode;view.querySelector('.mines-restart').textContent=t.again;decorateCard();render();}
  function build(){const main=document.getElementById('top');if(!main)return;view=document.querySelector('.mines-view');if(!view){view=document.createElement('section');view.className='mines-view';view.hidden=true;view.innerHTML=`<button type="button" class="mines-back"></button><div class="mines-head"><div><h2></h2><p class="mines-help"></p></div><button type="button" class="mines-new"></button></div><div class="mines-stats"><div><span class="mines-left-label"></span><strong data-mines-left>${M}</strong></div><div><span class="mines-time-label"></span><strong data-mines-time>0</strong></div><div><span class="mines-flags-label"></span><strong data-mines-flags>0</strong></div></div><button type="button" class="mines-mode"></button><div class="mines-wrap"><div class="mines-board" role="grid"></div><div class="mines-overlay" hidden><strong></strong><button type="button" class="mines-restart"></button></div></div>`;main.appendChild(view);view.querySelector('.mines-back').addEventListener('click',showGames);view.querySelector('.mines-new').addEventListener('click',newGame);view.querySelector('.mines-restart').addEventListener('click',newGame);view.querySelector('.mines-mode').addEventListener('click',()=>{flagMode=!flagMode;apply();});let hold=null,longPress=false;const board=view.querySelector('.mines-board');board.addEventListener('pointerdown',e=>{const c=e.target.closest('[data-mine-cell]');if(!c)return;longPress=false;hold=setTimeout(()=>{longPress=true;toggleFlag(Number(c.dataset.mineCell));navigator.vibrate?.(30);},480);});const clear=()=>{if(hold)clearTimeout(hold);hold=null;};board.addEventListener('pointerup',e=>{const c=e.target.closest('[data-mine-cell]');clear();if(!c||longPress)return;const i=Number(c.dataset.mineCell);flagMode?toggleFlag(i):openCell(i);});board.addEventListener('pointercancel',clear);board.addEventListener('contextmenu',e=>{const c=e.target.closest('[data-mine-cell]');if(c){e.preventDefault();toggleFlag(Number(c.dataset.mineCell));}});}
    document.addEventListener('click',e=>{const card=e.target.closest('.games-grid .game-card');if(!card)return;const all=[...document.querySelectorAll('.games-grid .game-card')];if(card.dataset.game==='minesweeper'||all.indexOf(card)===3){e.preventDefault();e.stopPropagation();decorateCard();showGame();}},true);newGame();apply();}
  new MutationObserver(()=>requestAnimationFrame(apply)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(build,0));else setTimeout(build,0);
})();