(()=>{
  const T={
    ru:{title:'Крестики-нолики',back:'← К списку игр',newGame:'Новая игра',you:'Вы',computer:'Компьютер',draws:'Ничьи',yourTurn:'Ваш ход',thinking:'Ход компьютера…',win:'Вы победили!',lose:'Компьютер победил',draw:'Ничья',hint:'Вы играете крестиками. Нажимайте на крупные клетки поля.',cell:'Клетка',play:'Играть'},
    en:{title:'Tic-tac-toe',back:'← Back to games',newGame:'New game',you:'You',computer:'Computer',draws:'Draws',yourTurn:'Your turn',thinking:'Computer is thinking…',win:'You win!',lose:'Computer wins',draw:'Draw',hint:'You play X. Tap a large square to make a move.',cell:'Cell',play:'Play'},
    fr:{title:'Morpion',back:'← Retour aux jeux',newGame:'Nouvelle partie',you:'Vous',computer:'Ordinateur',draws:'Nulles',yourTurn:'À vous',thinking:'L’ordinateur joue…',win:'Vous avez gagné !',lose:'L’ordinateur a gagné',draw:'Match nul',hint:'Vous jouez avec X. Touchez une grande case pour jouer.',cell:'Case',play:'Jouer'},
    de:{title:'Tic-Tac-Toe',back:'← Zurück zu den Spielen',newGame:'Neues Spiel',you:'Sie',computer:'Computer',draws:'Unentschieden',yourTurn:'Ihr Zug',thinking:'Computer zieht…',win:'Sie haben gewonnen!',lose:'Computer gewinnt',draw:'Unentschieden',hint:'Sie spielen X. Tippen Sie auf ein großes Feld.',cell:'Feld',play:'Spielen'}
  };
  const L=()=>T[document.documentElement.lang]?document.documentElement.lang:'ru';
  let view=null,board=Array(9).fill(''),locked=false,finished=false;
  let stats={you:0,computer:0,draws:0};
  try{stats={...stats,...JSON.parse(localStorage.getItem('lugovoy-ttt-stats')||'{}')}}catch{}

  const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
  function result(b){for(const w of wins){const [a,c,d]=w;if(b[a]&&b[a]===b[c]&&b[a]===b[d])return {winner:b[a],line:w};}return b.every(Boolean)?{winner:'draw',line:[]}:null;}
  function minimax(b,isMax){const r=result(b);if(r)return r.winner==='O'?10:r.winner==='X'?-10:0;let best=isMax?-Infinity:Infinity;for(let i=0;i<9;i++){if(b[i])continue;b[i]=isMax?'O':'X';const s=minimax(b,!isMax);b[i]='';best=isMax?Math.max(best,s):Math.min(best,s);}return best;}
  function computerMove(){if(finished)return;locked=true;setStatus(T[L()].thinking);setTimeout(()=>{let best=-Infinity,moves=[];for(let i=0;i<9;i++){if(board[i])continue;board[i]='O';const s=minimax(board,false);board[i]='';if(s>best){best=s;moves=[i]}else if(s===best)moves.push(i);}const pick=moves[Math.floor(Math.random()*moves.length)];if(pick!==undefined)board[pick]='O';locked=false;renderBoard();checkEnd();if(!finished)setStatus(T[L()].yourTurn);},260);}
  function playerMove(i){if(locked||finished||board[i])return;board[i]='X';renderBoard();if(!checkEnd())computerMove();}
  function checkEnd(){const r=result(board);if(!r)return false;finished=true;locked=true;view.querySelectorAll('.ttt-cell').forEach((c,i)=>{c.disabled=true;if(r.line.includes(i))c.classList.add('ttt-win-cell')});const t=T[L()];if(r.winner==='X'){stats.you++;setStatus(t.win)}else if(r.winner==='O'){stats.computer++;setStatus(t.lose)}else{stats.draws++;setStatus(t.draw)}localStorage.setItem('lugovoy-ttt-stats',JSON.stringify(stats));renderStats();return true;}
  function newGame(){board=Array(9).fill('');locked=false;finished=false;renderBoard();setStatus(T[L()].yourTurn);}
  function setStatus(s){const el=view?.querySelector('.ttt-status');if(el)el.textContent=s;}
  function renderBoard(){if(!view)return;view.querySelectorAll('.ttt-cell').forEach((c,i)=>{c.textContent=board[i];c.classList.toggle('is-x',board[i]==='X');c.classList.toggle('is-o',board[i]==='O');c.classList.remove('ttt-win-cell');c.disabled=!!board[i]||locked||finished;});}
  function renderStats(){if(!view)return;view.querySelector('[data-ttt-you]').textContent=stats.you;view.querySelector('[data-ttt-computer]').textContent=stats.computer;view.querySelector('[data-ttt-draws]').textContent=stats.draws;}
  function decorateCard(){const cards=document.querySelectorAll('.games-grid .game-card');const card=cards[4];if(!card)return;card.classList.add('game-ready');card.dataset.game='tictactoe';const badge=card.querySelector('.game-soon');if(badge)badge.textContent=T[L()].play;}
  function build(){const main=document.getElementById('top');if(!main)return;view=document.querySelector('.tictactoe-view');if(!view){view=document.createElement('section');view.className='tictactoe-view';view.hidden=true;view.innerHTML=`<button type="button" class="ttt-back"></button><div class="ttt-head"><div><h2></h2><p class="ttt-help"></p></div><button type="button" class="ttt-new"></button></div><div class="ttt-stats"><div><span class="ttt-you-label"></span><strong data-ttt-you>0</strong></div><div><span class="ttt-computer-label"></span><strong data-ttt-computer>0</strong></div><div><span class="ttt-draws-label"></span><strong data-ttt-draws>0</strong></div></div><div class="ttt-status" role="status" aria-live="polite"></div><div class="ttt-board" role="grid">${Array.from({length:9},(_,i)=>`<button type="button" class="ttt-cell" data-cell="${i}" role="gridcell"></button>`).join('')}</div>`;main.appendChild(view);view.querySelector('.ttt-back').addEventListener('click',showGames);view.querySelector('.ttt-new').addEventListener('click',newGame);view.querySelector('.ttt-board').addEventListener('click',e=>{const c=e.target.closest('.ttt-cell');if(c)playerMove(Number(c.dataset.cell));});}
    document.addEventListener('click',e=>{const card=e.target.closest('.games-grid .game-card');if(!card)return;const cards=[...document.querySelectorAll('.games-grid .game-card')];if(card.dataset.game==='tictactoe'||cards.indexOf(card)===4){e.preventDefault();e.stopPropagation();decorateCard();showGame();}},true);
    document.addEventListener('click',e=>{if(e.target.closest('[data-action="games"],.games-back,.lang-option'))setTimeout(decorateCard,0);},true);
    apply();decorateCard();newGame();renderStats();
  }
  function hideOtherViews(){document.querySelector('.new-home-nav')?.setAttribute('hidden','');document.querySelector('.games-view')?.setAttribute('hidden','');document.querySelector('.game2048-view')?.setAttribute('hidden','');document.querySelector('.snake-view')?.setAttribute('hidden','');document.querySelector('.new-ui-search-view')?.setAttribute('hidden','');}
  function showGame(){hideOtherViews();view.hidden=false;view.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>view.querySelector('.ttt-cell:not(:disabled)')?.focus({preventScroll:true}),180);}
  function showGames(){view.hidden=true;const games=document.querySelector('.games-view');if(games){games.hidden=false;decorateCard();games.scrollIntoView({behavior:'smooth',block:'start'});}}
  function apply(){if(!view)return;const t=T[L()];view.querySelector('h2').textContent=`⭕ ${t.title}`;view.querySelector('.ttt-back').textContent=t.back;view.querySelector('.ttt-new').textContent=t.newGame;view.querySelector('.ttt-help').textContent=t.hint;view.querySelector('.ttt-you-label').textContent=t.you;view.querySelector('.ttt-computer-label').textContent=t.computer;view.querySelector('.ttt-draws-label').textContent=t.draws;view.querySelectorAll('.ttt-cell').forEach((c,i)=>c.setAttribute('aria-label',`${t.cell} ${i+1}`));if(!finished&&!locked)setStatus(t.yourTurn);decorateCard();}
  new MutationObserver(()=>requestAnimationFrame(apply)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(build,0));else setTimeout(build,0);
})();